# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Math_PlusOrMinus100.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Math_PlusOrMinus100(object):
    def setupUi(self, Math_PlusOrMinus100):
        Math_PlusOrMinus100.setObjectName("Math_PlusOrMinus100")
        Math_PlusOrMinus100.resize(980, 522)
        Math_PlusOrMinus100.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gridLayout_3 = QtWidgets.QGridLayout(Math_PlusOrMinus100)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(Math_PlusOrMinus100)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setMinimumSize(QtCore.QSize(70, 50))
        self.label_5.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.labScore = QtWidgets.QLabel(self.widget_2)
        self.labScore.setMinimumSize(QtCore.QSize(70, 50))
        self.labScore.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)
        self.labScore.setFont(font)
        self.labScore.setAlignment(QtCore.Qt.AlignCenter)
        self.labScore.setObjectName("labScore")
        self.gridLayout.addWidget(self.labScore, 1, 3, 1, 1)
        self.labPixRight = QtWidgets.QLabel(self.widget_2)
        self.labPixRight.setMinimumSize(QtCore.QSize(70, 50))
        self.labPixRight.setMaximumSize(QtCore.QSize(70, 50))
        self.labPixRight.setText("")
        self.labPixRight.setObjectName("labPixRight")
        self.gridLayout.addWidget(self.labPixRight, 0, 1, 1, 1)
        self.labRight = QtWidgets.QLabel(self.widget_2)
        self.labRight.setMinimumSize(QtCore.QSize(70, 50))
        self.labRight.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)
        self.labRight.setFont(font)
        self.labRight.setAlignment(QtCore.Qt.AlignCenter)
        self.labRight.setObjectName("labRight")
        self.gridLayout.addWidget(self.labRight, 1, 1, 1, 1)
        self.labTime = QtWidgets.QLabel(self.widget_2)
        self.labTime.setMinimumSize(QtCore.QSize(149, 149))
        self.labTime.setMaximumSize(QtCore.QSize(149, 149))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(43)
        self.labTime.setFont(font)
        self.labTime.setScaledContents(False)
        self.labTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labTime.setObjectName("labTime")
        self.gridLayout.addWidget(self.labTime, 0, 8, 3, 1)
        self.labPixWrong = QtWidgets.QLabel(self.widget_2)
        self.labPixWrong.setMinimumSize(QtCore.QSize(70, 50))
        self.labPixWrong.setMaximumSize(QtCore.QSize(70, 50))
        self.labPixWrong.setText("")
        self.labPixWrong.setObjectName("labPixWrong")
        self.gridLayout.addWidget(self.labPixWrong, 0, 2, 1, 1)
        self.labMovie = QtWidgets.QLabel(self.widget_2)
        self.labMovie.setMinimumSize(QtCore.QSize(149, 149))
        self.labMovie.setMaximumSize(QtCore.QSize(149, 149))
        self.labMovie.setText("")
        self.labMovie.setScaledContents(True)
        self.labMovie.setObjectName("labMovie")
        self.gridLayout.addWidget(self.labMovie, 0, 5, 3, 1)
        self.labWrong = QtWidgets.QLabel(self.widget_2)
        self.labWrong.setMinimumSize(QtCore.QSize(70, 50))
        self.labWrong.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)
        self.labWrong.setFont(font)
        self.labWrong.setAlignment(QtCore.Qt.AlignCenter)
        self.labWrong.setObjectName("labWrong")
        self.gridLayout.addWidget(self.labWrong, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnTimeStart = QtWidgets.QPushButton(self.widget_3)
        self.btnTimeStart.setMinimumSize(QtCore.QSize(36, 36))
        self.btnTimeStart.setMaximumSize(QtCore.QSize(36, 36))
        self.btnTimeStart.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnTimeStart.setText("")
        self.btnTimeStart.setCheckable(False)
        self.btnTimeStart.setChecked(False)
        self.btnTimeStart.setObjectName("btnTimeStart")
        self.horizontalLayout_10.addWidget(self.btnTimeStart)
        self.btnTimeStop = QtWidgets.QPushButton(self.widget_3)
        self.btnTimeStop.setMinimumSize(QtCore.QSize(36, 36))
        self.btnTimeStop.setMaximumSize(QtCore.QSize(36, 36))
        self.btnTimeStop.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnTimeStop.setText("")
        self.btnTimeStop.setCheckable(False)
        self.btnTimeStop.setObjectName("btnTimeStop")
        self.horizontalLayout_10.addWidget(self.btnTimeStop)
        self.gridLayout.addWidget(self.widget_3, 1, 7, 1, 1)
        self.sBoxTimeChange = QtWidgets.QSpinBox(self.widget_2)
        self.sBoxTimeChange.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.sBoxTimeChange.setFont(font)
        self.sBoxTimeChange.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.sBoxTimeChange.setAccessibleName("")
        self.sBoxTimeChange.setAccessibleDescription("")
        self.sBoxTimeChange.setWrapping(True)
        self.sBoxTimeChange.setFrame(False)
        self.sBoxTimeChange.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxTimeChange.setReadOnly(False)
        self.sBoxTimeChange.setProperty("showGroupSeparator", False)
        self.sBoxTimeChange.setMaximum(10)
        self.sBoxTimeChange.setObjectName("spinBox")
        self.gridLayout.addWidget(self.sBoxTimeChange, 0, 7, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 2)
        self.widget = QtWidgets.QWidget(Math_PlusOrMinus100)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(10, 40, 10, 0)
        self.gridLayout_4.setHorizontalSpacing(30)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_19 = QtWidgets.QLabel(self.widget_6)
        self.label_19.setMinimumSize(QtCore.QSize(65, 50))
        self.label_19.setMaximumSize(QtCore.QSize(65, 50))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.gridLayout_4.addWidget(self.widget_6, 0, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setMinimumSize(QtCore.QSize(65, 50))
        self.label_9.setMaximumSize(QtCore.QSize(65, 50))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout_4.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setMinimumSize(QtCore.QSize(65, 50))
        self.label_14.setMaximumSize(QtCore.QSize(65, 50))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.gridLayout_4.addWidget(self.widget_5, 0, 1, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.widget)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_44 = QtWidgets.QLabel(self.widget_11)
        self.label_44.setMinimumSize(QtCore.QSize(65, 50))
        self.label_44.setMaximumSize(QtCore.QSize(65, 50))
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_8.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_8.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_8.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_8.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_8.addWidget(self.label_48)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_8.addWidget(self.lineEdit_8)
        self.gridLayout_4.addWidget(self.widget_11, 2, 1, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.widget)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_39 = QtWidgets.QLabel(self.widget_10)
        self.label_39.setMinimumSize(QtCore.QSize(65, 50))
        self.label_39.setMaximumSize(QtCore.QSize(65, 50))
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_7.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_7.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_7.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_7.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_7.addWidget(self.label_43)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_7.addWidget(self.lineEdit_7)
        self.gridLayout_4.addWidget(self.widget_10, 2, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.widget_7)
        self.label_24.setMinimumSize(QtCore.QSize(65, 50))
        self.label_24.setMaximumSize(QtCore.QSize(65, 50))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_4.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.gridLayout_4.addWidget(self.widget_7, 1, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_29 = QtWidgets.QLabel(self.widget_8)
        self.label_29.setMinimumSize(QtCore.QSize(65, 50))
        self.label_29.setMaximumSize(QtCore.QSize(65, 50))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_5.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_5.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_5.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_5.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_5.addWidget(self.label_33)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.gridLayout_4.addWidget(self.widget_8, 1, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.widget)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_34 = QtWidgets.QLabel(self.widget_9)
        self.label_34.setMinimumSize(QtCore.QSize(65, 50))
        self.label_34.setMaximumSize(QtCore.QSize(65, 50))
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_6.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_6.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_6.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_6.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_6.addWidget(self.label_38)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.gridLayout_4.addWidget(self.widget_9, 1, 2, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.widget)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_49 = QtWidgets.QLabel(self.widget_12)
        self.label_49.setMinimumSize(QtCore.QSize(65, 50))
        self.label_49.setMaximumSize(QtCore.QSize(65, 50))
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_9.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_9.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_9.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_9.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_9.addWidget(self.label_53)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_12)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(70, 50))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_9.addWidget(self.lineEdit_9)
        self.gridLayout_4.addWidget(self.widget_12, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.widget_13 = QtWidgets.QWidget(Math_PlusOrMinus100)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_11.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.btnCommit = QtWidgets.QPushButton(self.widget_13)
        self.btnCommit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.btnCommit.setFont(font)
        self.btnCommit.setObjectName("btnCommit")
        self.horizontalLayout_11.addWidget(self.btnCommit)
        self.gridLayout_3.addWidget(self.widget_13, 2, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 2)
        self.gridLayout_3.setRowStretch(1, 5)

        self.retranslateUi(Math_PlusOrMinus100)
        QtCore.QMetaObject.connectSlotsByName(Math_PlusOrMinus100)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit, self.lineEdit_2)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        Math_PlusOrMinus100.setTabOrder(self.lineEdit_9, self.btnCommit)
        Math_PlusOrMinus100.setTabOrder(self.btnCommit, self.sBoxTimeChange)

    def retranslateUi(self, Math_PlusOrMinus100):
        _translate = QtCore.QCoreApplication.translate
        Math_PlusOrMinus100.setWindowTitle(_translate("Math_PlusOrMinus100", "Form"))
        self.label_5.setText(_translate("Math_PlusOrMinus100", "总分"))
        self.labScore.setText(_translate("Math_PlusOrMinus100", "0"))
        self.labRight.setText(_translate("Math_PlusOrMinus100", "0"))
        self.labTime.setText(_translate("Math_PlusOrMinus100", "0"))
        self.labWrong.setText(_translate("Math_PlusOrMinus100", "0"))
        self.sBoxTimeChange.setSuffix(_translate("Math_PlusOrMinus100", "分钟"))
        self.label_19.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_20.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_21.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_22.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_23.setText(_translate("Math_PlusOrMinus100", "="))
        self.label_9.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_10.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_12.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_13.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_11.setText(_translate("Math_PlusOrMinus100", "="))
        self.label_14.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_15.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_16.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_17.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_18.setText(_translate("Math_PlusOrMinus100", "="))
        self.label_44.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_45.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_46.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_47.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_48.setText(_translate("Math_PlusOrMinus100", "="))
        self.label_39.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_40.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_41.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_42.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_43.setText(_translate("Math_PlusOrMinus100", "="))
        self.label_24.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_25.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_26.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_27.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_28.setText(_translate("Math_PlusOrMinus100", "="))
        self.label_29.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_30.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_31.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_32.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_33.setText(_translate("Math_PlusOrMinus100", "="))
        self.label_34.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_35.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_36.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_37.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_38.setText(_translate("Math_PlusOrMinus100", "="))
        self.label_49.setText(_translate("Math_PlusOrMinus100", "图片"))
        self.label_50.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_51.setText(_translate("Math_PlusOrMinus100", "+"))
        self.label_52.setText(_translate("Math_PlusOrMinus100", "99"))
        self.label_53.setText(_translate("Math_PlusOrMinus100", "="))
        self.btnCommit.setText(_translate("Math_PlusOrMinus100", "提交作业"))


