# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Cn_HanZi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Cn_HanZi(object):
    def setupUi(self, Cn_HanZi):
        Cn_HanZi.setObjectName("Cn_HanZi")
        Cn_HanZi.resize(980, 520)
        Cn_HanZi.setMinimumSize(QtCore.QSize(980, 520))
        Cn_HanZi.setMaximumSize(QtCore.QSize(980, 520))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Cn_HanZi)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Cn_HanZi)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widLeftScrollArea = QtWidgets.QWidget()
        self.widLeftScrollArea.setGeometry(QtCore.QRect(0, 0, 652, 500))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.widLeftScrollArea.setFont(font)
        self.widLeftScrollArea.setObjectName("widLeftScrollArea")
        self.gridLeft = QtWidgets.QGridLayout(self.widLeftScrollArea)
        self.gridLeft.setContentsMargins(0, 20, 0, 0)
        self.gridLeft.setObjectName("gridLeft")
        self.scrollArea.setWidget(self.widLeftScrollArea)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.widRight = QtWidgets.QWidget(Cn_HanZi)
        self.widRight.setMinimumSize(QtCore.QSize(258, 0))
        self.widRight.setMaximumSize(QtCore.QSize(258, 16777215))
        self.widRight.setObjectName("widRight")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widRight)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.widRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 2, 0, 1, 1)
        self.btnStart = QtWidgets.QPushButton(self.widRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_3.addWidget(self.btnStart, 2, 1, 1, 1)
        self.labPinYin = QtWidgets.QLabel(self.widRight)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(40)
        self.labPinYin.setFont(font)
        self.labPinYin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labPinYin.setAlignment(QtCore.Qt.AlignCenter)
        self.labPinYin.setObjectName("labPinYin")
        self.gridLayout_3.addWidget(self.labPinYin, 0, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.labGif = QtWidgets.QLabel(self.widRight)
        self.labGif.setMinimumSize(QtCore.QSize(0, 258))
        self.labGif.setMaximumSize(QtCore.QSize(16777215, 258))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(40)
        self.labGif.setFont(font)
        self.labGif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labGif.setScaledContents(True)
        self.labGif.setObjectName("labGif")
        self.gridLayout_3.addWidget(self.labGif, 1, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.widRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 4, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 5, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 3)
        self.gridLayout_3.setRowStretch(1, 12)
        self.gridLayout_3.setRowStretch(2, 2)
        self.gridLayout_3.setRowStretch(3, 2)
        self.gridLayout_3.setRowStretch(4, 2)
        self.gridLayout_3.setRowStretch(5, 1)
        self.horizontalLayout.addWidget(self.widRight)

        self.retranslateUi(Cn_HanZi)
        QtCore.QMetaObject.connectSlotsByName(Cn_HanZi)

    def retranslateUi(self, Cn_HanZi):
        _translate = QtCore.QCoreApplication.translate
        Cn_HanZi.setWindowTitle(_translate("Cn_HanZi", "Form"))
        self.pushButton.setText(_translate("Cn_HanZi", "首页"))
        self.btnStart.setText(_translate("Cn_HanZi", "开始滚动"))
        self.labPinYin.setText(_translate("Cn_HanZi", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">拼音</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Cn_HanZi", "添加"))
        self.labGif.setText(_translate("Cn_HanZi", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">笔画</span></p><p align=\"center\"><span style=\" color:#aaaaff;\">演示</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Cn_HanZi", "输入汉字"))
        self.pushButton_4.setText(_translate("Cn_HanZi", "删除"))
        self.checkBox.setText(_translate("Cn_HanZi", "开启/关闭语音"))

