# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Puzzle.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Puzzle(object):
    def setupUi(self, Puzzle):
        Puzzle.setObjectName("Puzzle")
        Puzzle.resize(980, 520)
        Puzzle.setStyleSheet("")
        self.label_9 = QtWidgets.QLabel(Puzzle)
        self.label_9.setGeometry(QtCore.QRect(210, 204, 100, 100))
        self.label_9.setMinimumSize(QtCore.QSize(100, 100))
        self.label_9.setMaximumSize(QtCore.QSize(100, 100))
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_9.setAcceptDrops(False)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(Puzzle)
        self.label_11.setGeometry(QtCore.QRect(108, 306, 100, 100))
        self.label_11.setMinimumSize(QtCore.QSize(100, 100))
        self.label_11.setMaximumSize(QtCore.QSize(100, 100))
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_11.setAcceptDrops(False)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(Puzzle)
        self.label_16.setGeometry(QtCore.QRect(108, 408, 100, 100))
        self.label_16.setMinimumSize(QtCore.QSize(100, 100))
        self.label_16.setMaximumSize(QtCore.QSize(100, 100))
        self.label_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_16.setAcceptDrops(False)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_14 = QtWidgets.QLabel(Puzzle)
        self.label_14.setGeometry(QtCore.QRect(312, 408, 100, 100))
        self.label_14.setMinimumSize(QtCore.QSize(100, 100))
        self.label_14.setMaximumSize(QtCore.QSize(100, 100))
        self.label_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_14.setAcceptDrops(False)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_2 = QtWidgets.QLabel(Puzzle)
        self.label_2.setGeometry(QtCore.QRect(108, 102, 100, 100))
        self.label_2.setMinimumSize(QtCore.QSize(100, 100))
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2.setAcceptDrops(False)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Puzzle)
        self.label_3.setGeometry(QtCore.QRect(210, 102, 100, 100))
        self.label_3.setMinimumSize(QtCore.QSize(100, 100))
        self.label_3.setMaximumSize(QtCore.QSize(100, 100))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setAcceptDrops(False)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_13 = QtWidgets.QLabel(Puzzle)
        self.label_13.setGeometry(QtCore.QRect(312, 306, 100, 100))
        self.label_13.setMinimumSize(QtCore.QSize(100, 100))
        self.label_13.setMaximumSize(QtCore.QSize(100, 100))
        self.label_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_13.setAcceptDrops(False)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(Puzzle)
        self.label_7.setGeometry(QtCore.QRect(6, 408, 100, 100))
        self.label_7.setMinimumSize(QtCore.QSize(100, 100))
        self.label_7.setMaximumSize(QtCore.QSize(100, 100))
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_7.setAcceptDrops(False)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Puzzle)
        self.label_8.setGeometry(QtCore.QRect(108, 204, 100, 100))
        self.label_8.setMinimumSize(QtCore.QSize(100, 100))
        self.label_8.setMaximumSize(QtCore.QSize(100, 100))
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_8.setAcceptDrops(False)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(Puzzle)
        self.label_6.setGeometry(QtCore.QRect(6, 306, 100, 100))
        self.label_6.setMinimumSize(QtCore.QSize(100, 100))
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_6.setAcceptDrops(False)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(Puzzle)
        self.label_15.setGeometry(QtCore.QRect(210, 408, 100, 100))
        self.label_15.setMinimumSize(QtCore.QSize(100, 100))
        self.label_15.setMaximumSize(QtCore.QSize(100, 100))
        self.label_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_15.setAcceptDrops(False)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(Puzzle)
        self.label_12.setGeometry(QtCore.QRect(210, 306, 100, 100))
        self.label_12.setMinimumSize(QtCore.QSize(100, 100))
        self.label_12.setMaximumSize(QtCore.QSize(100, 100))
        self.label_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_12.setAcceptDrops(False)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_5 = QtWidgets.QLabel(Puzzle)
        self.label_5.setGeometry(QtCore.QRect(6, 204, 100, 100))
        self.label_5.setMinimumSize(QtCore.QSize(100, 100))
        self.label_5.setMaximumSize(QtCore.QSize(100, 100))
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setAcceptDrops(False)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Puzzle)
        self.label.setGeometry(QtCore.QRect(6, 102, 100, 100))
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setAcceptDrops(False)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Puzzle)
        self.label_4.setGeometry(QtCore.QRect(312, 102, 100, 100))
        self.label_4.setMinimumSize(QtCore.QSize(100, 100))
        self.label_4.setMaximumSize(QtCore.QSize(100, 100))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setAcceptDrops(False)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(Puzzle)
        self.label_10.setGeometry(QtCore.QRect(312, 204, 100, 100))
        self.label_10.setMinimumSize(QtCore.QSize(100, 100))
        self.label_10.setMaximumSize(QtCore.QSize(100, 100))
        self.label_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_10.setAcceptDrops(False)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.wid15 = QtWidgets.QWidget(Puzzle)
        self.wid15.setGeometry(QtCore.QRect(870, 404, 100, 100))
        self.wid15.setMinimumSize(QtCore.QSize(100, 100))
        self.wid15.setMaximumSize(QtCore.QSize(100, 100))
        self.wid15.setObjectName("wid15")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.wid15)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.wid1 = QtWidgets.QWidget(Puzzle)
        self.wid1.setGeometry(QtCore.QRect(670, 104, 100, 100))
        self.wid1.setMinimumSize(QtCore.QSize(100, 100))
        self.wid1.setMaximumSize(QtCore.QSize(100, 100))
        self.wid1.setObjectName("wid1")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.wid1)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.wid2 = QtWidgets.QWidget(Puzzle)
        self.wid2.setGeometry(QtCore.QRect(770, 104, 100, 100))
        self.wid2.setMinimumSize(QtCore.QSize(100, 100))
        self.wid2.setMaximumSize(QtCore.QSize(100, 100))
        self.wid2.setObjectName("wid2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.wid2)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.wid3 = QtWidgets.QWidget(Puzzle)
        self.wid3.setGeometry(QtCore.QRect(870, 104, 100, 100))
        self.wid3.setMinimumSize(QtCore.QSize(100, 100))
        self.wid3.setMaximumSize(QtCore.QSize(100, 100))
        self.wid3.setObjectName("wid3")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.wid3)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.wid11 = QtWidgets.QWidget(Puzzle)
        self.wid11.setGeometry(QtCore.QRect(870, 304, 100, 100))
        self.wid11.setMinimumSize(QtCore.QSize(100, 100))
        self.wid11.setMaximumSize(QtCore.QSize(100, 100))
        self.wid11.setObjectName("wid11")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.wid11)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.wid12 = QtWidgets.QWidget(Puzzle)
        self.wid12.setGeometry(QtCore.QRect(570, 404, 100, 100))
        self.wid12.setMinimumSize(QtCore.QSize(100, 100))
        self.wid12.setMaximumSize(QtCore.QSize(100, 100))
        self.wid12.setObjectName("wid12")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.wid12)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.wid8 = QtWidgets.QWidget(Puzzle)
        self.wid8.setGeometry(QtCore.QRect(570, 304, 100, 100))
        self.wid8.setMinimumSize(QtCore.QSize(100, 100))
        self.wid8.setMaximumSize(QtCore.QSize(100, 100))
        self.wid8.setObjectName("wid8")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.wid8)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.wid0 = QtWidgets.QWidget(Puzzle)
        self.wid0.setGeometry(QtCore.QRect(570, 104, 100, 100))
        self.wid0.setMinimumSize(QtCore.QSize(100, 100))
        self.wid0.setMaximumSize(QtCore.QSize(100, 100))
        self.wid0.setObjectName("wid0")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.wid0)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.wid5 = QtWidgets.QWidget(Puzzle)
        self.wid5.setGeometry(QtCore.QRect(670, 204, 100, 100))
        self.wid5.setMinimumSize(QtCore.QSize(100, 100))
        self.wid5.setMaximumSize(QtCore.QSize(100, 100))
        self.wid5.setObjectName("wid5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.wid5)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.wid14 = QtWidgets.QWidget(Puzzle)
        self.wid14.setGeometry(QtCore.QRect(770, 404, 100, 100))
        self.wid14.setMinimumSize(QtCore.QSize(100, 100))
        self.wid14.setMaximumSize(QtCore.QSize(100, 100))
        self.wid14.setObjectName("wid14")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.wid14)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.wid9 = QtWidgets.QWidget(Puzzle)
        self.wid9.setGeometry(QtCore.QRect(670, 304, 100, 100))
        self.wid9.setMinimumSize(QtCore.QSize(100, 100))
        self.wid9.setMaximumSize(QtCore.QSize(100, 100))
        self.wid9.setObjectName("wid9")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.wid9)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.wid7 = QtWidgets.QWidget(Puzzle)
        self.wid7.setGeometry(QtCore.QRect(870, 204, 100, 100))
        self.wid7.setMinimumSize(QtCore.QSize(100, 100))
        self.wid7.setMaximumSize(QtCore.QSize(100, 100))
        self.wid7.setObjectName("wid7")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.wid7)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.wid6 = QtWidgets.QWidget(Puzzle)
        self.wid6.setGeometry(QtCore.QRect(770, 204, 100, 100))
        self.wid6.setMinimumSize(QtCore.QSize(100, 100))
        self.wid6.setMaximumSize(QtCore.QSize(100, 100))
        self.wid6.setObjectName("wid6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.wid6)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.wid10 = QtWidgets.QWidget(Puzzle)
        self.wid10.setGeometry(QtCore.QRect(770, 304, 100, 100))
        self.wid10.setMinimumSize(QtCore.QSize(100, 100))
        self.wid10.setMaximumSize(QtCore.QSize(100, 100))
        self.wid10.setObjectName("wid10")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.wid10)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.wid13 = QtWidgets.QWidget(Puzzle)
        self.wid13.setGeometry(QtCore.QRect(670, 404, 100, 100))
        self.wid13.setMinimumSize(QtCore.QSize(100, 100))
        self.wid13.setMaximumSize(QtCore.QSize(100, 100))
        self.wid13.setObjectName("wid13")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.wid13)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.wid4 = QtWidgets.QWidget(Puzzle)
        self.wid4.setGeometry(QtCore.QRect(570, 204, 100, 100))
        self.wid4.setMinimumSize(QtCore.QSize(100, 100))
        self.wid4.setMaximumSize(QtCore.QSize(100, 100))
        self.wid4.setObjectName("wid4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.wid4)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frameBorder = QtWidgets.QFrame(Puzzle)
        self.frameBorder.setGeometry(QtCore.QRect(427, 184, 128, 128))
        self.frameBorder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBorder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBorder.setObjectName("frameBorder")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameBorder)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnPix = QtWidgets.QPushButton(self.frameBorder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPix.sizePolicy().hasHeightForWidth())
        self.btnPix.setSizePolicy(sizePolicy)
        self.btnPix.setText("")
        self.btnPix.setObjectName("btnPix")
        self.horizontalLayout_2.addWidget(self.btnPix)
        self.btnUpdataPix = QtWidgets.QPushButton(Puzzle)
        self.btnUpdataPix.setGeometry(QtCore.QRect(456, 464, 70, 50))
        self.btnUpdataPix.setText("")
        self.btnUpdataPix.setObjectName("btnUpdataPix")
        self.frameBg = QtWidgets.QFrame(Puzzle)
        self.frameBg.setGeometry(QtCore.QRect(570, 104, 400, 400))
        self.frameBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBg.setObjectName("frameBg")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Puzzle)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 961, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.labCount = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labCount.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)
        self.labCount.setFont(font)
        self.labCount.setAlignment(QtCore.Qt.AlignCenter)
        self.labCount.setObjectName("labCount")
        self.horizontalLayout.addWidget(self.labCount)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(Puzzle)
        self.frame.setGeometry(QtCore.QRect(59, 0, 881, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frameAnimat = QtWidgets.QFrame(Puzzle)
        self.frameAnimat.setGeometry(QtCore.QRect(440, 330, 95, 61))
        self.frameAnimat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAnimat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAnimat.setObjectName("frameAnimat")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameAnimat)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnAnimat = QtWidgets.QPushButton(self.frameAnimat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnimat.sizePolicy().hasHeightForWidth())
        self.btnAnimat.setSizePolicy(sizePolicy)
        self.btnAnimat.setText("")
        self.btnAnimat.setObjectName("btnAnimat")
        self.horizontalLayout_3.addWidget(self.btnAnimat)
        self.btnFinish = QtWidgets.QPushButton(Puzzle)
        self.btnFinish.setGeometry(QtCore.QRect(450, 410, 75, 23))
        self.btnFinish.setText("")
        self.btnFinish.setObjectName("btnFinish")
        self.frameBg.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.label_16.raise_()
        self.label_14.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_13.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_6.raise_()
        self.label_15.raise_()
        self.label_12.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_10.raise_()
        self.wid15.raise_()
        self.wid1.raise_()
        self.wid2.raise_()
        self.wid3.raise_()
        self.wid11.raise_()
        self.wid12.raise_()
        self.wid8.raise_()
        self.wid0.raise_()
        self.wid5.raise_()
        self.wid14.raise_()
        self.wid9.raise_()
        self.wid7.raise_()
        self.wid6.raise_()
        self.wid10.raise_()
        self.wid13.raise_()
        self.wid4.raise_()
        self.frameBorder.raise_()
        self.btnUpdataPix.raise_()
        self.horizontalLayoutWidget.raise_()
        self.frame.raise_()
        self.frameAnimat.raise_()
        self.btnFinish.raise_()

        self.retranslateUi(Puzzle)
        QtCore.QMetaObject.connectSlotsByName(Puzzle)

    def retranslateUi(self, Puzzle):
        _translate = QtCore.QCoreApplication.translate
        Puzzle.setWindowTitle(_translate("Puzzle", "Form"))
        self.label_18.setText(_translate("Puzzle", "操作次数：\n"
"（16次为最佳）"))
        self.labCount.setText(_translate("Puzzle", "0"))


