# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Math.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Math(object):
    def setupUi(self, Math):
        Math.setObjectName("Math")
        Math.resize(1249, 580)
        Math.setStyleSheet("QPushButton {background-color: transparent; boder: none; outline:none;}\n"
"\n"
"QLineEdit {background-color: white; border: 2px solid gray; border-radius: 5px; color: rgb(0, 150, 0);}\n"
"QLineEdit:focus {background-color: lightgray; border: 2px solid red;}\n"
"\n"
"#btnMini {border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;}\n"
"#btnMini:hover {background-color: rgba(255, 255, 255, 120);}\n"
"\n"
"#btnClose {border-bottom-left-radius: 5px;}\n"
"#btnClose:hover {background-color: rgba(255, 0, 0, 150);}\n"
"\n"
"#btnUpdate {border-top-right-radius: 5px;}\n"
"#btnCommit {border-top-left-radius: 5px;}\n"
"#btnUpdate:hover, #btnCommit:hover {background-color: rgb(85, 85, 255);}\n"
"#btnCommit:focus {background-color: rgb(85, 85, 255);}\n"
"#btnNextPage {border-radius: 5px;}\n"
"#btnNextPage:hover {background-color: rgb(85, 85, 255);}\n"
"\n"
"QWidget#Math {background-color: rgb(170, 255, 155);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Math)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Math)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 70))
        self.label_3.setMaximumSize(QtCore.QSize(200, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.labTimer = QtWidgets.QLabel(self.widget)
        self.labTimer.setMinimumSize(QtCore.QSize(70, 0))
        self.labTimer.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(30)
        self.labTimer.setFont(font)
        self.labTimer.setStyleSheet("color: rgb(255, 85, 255);")
        self.labTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.labTimer.setObjectName("labTimer")
        self.horizontalLayout.addWidget(self.labTimer)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labMedal = QtWidgets.QLabel(self.widget)
        self.labMedal.setEnabled(False)
        self.labMedal.setMinimumSize(QtCore.QSize(70, 70))
        self.labMedal.setMaximumSize(QtCore.QSize(70, 70))
        self.labMedal.setText("")
        self.labMedal.setPixmap(QtGui.QPixmap(":/medal.png"))
        self.labMedal.setObjectName("labMedal")
        self.horizontalLayout.addWidget(self.labMedal)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.labRight = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labRight.sizePolicy().hasHeightForWidth())
        self.labRight.setSizePolicy(sizePolicy)
        self.labRight.setMinimumSize(QtCore.QSize(60, 0))
        self.labRight.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labRight.setFont(font)
        self.labRight.setStyleSheet("color: rgb(0, 255, 0);")
        self.labRight.setAlignment(QtCore.Qt.AlignCenter)
        self.labRight.setObjectName("labRight")
        self.horizontalLayout.addWidget(self.labRight)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.labWrong = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labWrong.sizePolicy().hasHeightForWidth())
        self.labWrong.setSizePolicy(sizePolicy)
        self.labWrong.setMinimumSize(QtCore.QSize(60, 0))
        self.labWrong.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labWrong.setFont(font)
        self.labWrong.setStyleSheet("color: rgb(255, 0, 0);")
        self.labWrong.setAlignment(QtCore.Qt.AlignCenter)
        self.labWrong.setObjectName("labWrong")
        self.horizontalLayout.addWidget(self.labWrong)
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnMini = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMini.sizePolicy().hasHeightForWidth())
        self.btnMini.setSizePolicy(sizePolicy)
        self.btnMini.setMinimumSize(QtCore.QSize(40, 40))
        self.btnMini.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnMini.setFont(font)
        self.btnMini.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMini.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMini.setStyleSheet("")
        self.btnMini.setObjectName("btnMini")
        self.horizontalLayout_4.addWidget(self.btnMini)
        self.btnClose = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setMinimumSize(QtCore.QSize(40, 40))
        self.btnClose.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnClose.setFont(font)
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClose.setStyleSheet("")
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_4.addWidget(self.btnClose)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)
        self.scrollArea = QtWidgets.QScrollArea(Math)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1247, 448))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.scrollLayout.setObjectName("scrollLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.widget_3 = QtWidgets.QWidget(Math)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnUpdate = QtWidgets.QPushButton(self.widget_3)
        self.btnUpdate.setMinimumSize(QtCore.QSize(200, 50))
        self.btnUpdate.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUpdate.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnUpdate.setStyleSheet("")
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout_2.addWidget(self.btnUpdate)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btnCommit = QtWidgets.QPushButton(self.widget_3)
        self.btnCommit.setMinimumSize(QtCore.QSize(200, 50))
        self.btnCommit.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.btnCommit.setFont(font)
        self.btnCommit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCommit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCommit.setStyleSheet("")
        self.btnCommit.setObjectName("btnCommit")
        self.horizontalLayout_2.addWidget(self.btnCommit)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(Math)
        self.btnClose.clicked.connect(Math.close)
        self.btnMini.clicked.connect(Math.showMinimized)
        self.btnCommit.clicked.connect(Math.setFocus)
        QtCore.QMetaObject.connectSlotsByName(Math)

    def retranslateUi(self, Math):
        _translate = QtCore.QCoreApplication.translate
        Math.setWindowTitle(_translate("Math", "小学数学连加连减混合练习"))
        self.label_3.setText(_translate("Math", "倒计时："))
        self.labTimer.setText(_translate("Math", "180"))
        self.label_2.setText(_translate("Math", "正确"))
        self.labRight.setText(_translate("Math", "0"))
        self.label_4.setText(_translate("Math", "题，错误"))
        self.labWrong.setText(_translate("Math", "0"))
        self.label_5.setText(_translate("Math", "题"))
        self.label_6.setText(_translate("Math", "（共72题）"))
        self.btnMini.setText(_translate("Math", "-"))
        self.btnClose.setText(_translate("Math", "×"))
        self.btnUpdate.setText(_translate("Math", "刷新"))
        self.btnCommit.setText(_translate("Math", "提交"))
import math_rc
