# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hanzi.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HanZi(object):
    def setupUi(self, HanZi):
        HanZi.setObjectName("HanZi")
        HanZi.resize(980, 520)
        HanZi.setMinimumSize(QtCore.QSize(0, 0))
        HanZi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(HanZi)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(HanZi)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 694, 514))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.gridLeft = QtWidgets.QGridLayout(self.widget)
        self.gridLeft.setContentsMargins(-1, 20, -1, -1)
        self.gridLeft.setObjectName("gridLeft")
        self.scrollArea.setWidget(self.widget)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.labPinYin = QtWidgets.QLabel(HanZi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labPinYin.sizePolicy().hasHeightForWidth())
        self.labPinYin.setSizePolicy(sizePolicy)
        self.labPinYin.setMinimumSize(QtCore.QSize(258, 60))
        self.labPinYin.setMaximumSize(QtCore.QSize(258, 60))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(40)
        self.labPinYin.setFont(font)
        self.labPinYin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labPinYin.setAlignment(QtCore.Qt.AlignCenter)
        self.labPinYin.setObjectName("labPinYin")
        self.gridLayout.addWidget(self.labPinYin, 0, 0, 1, 2)
        self.labGif = QtWidgets.QLabel(HanZi)
        self.labGif.setMinimumSize(QtCore.QSize(258, 258))
        self.labGif.setMaximumSize(QtCore.QSize(258, 258))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(40)
        self.labGif.setFont(font)
        self.labGif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labGif.setScaledContents(True)
        self.labGif.setObjectName("labGif")
        self.gridLayout.addWidget(self.labGif, 1, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(HanZi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(126, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(126, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.btnStart = QtWidgets.QPushButton(HanZi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        self.btnStart.setMinimumSize(QtCore.QSize(126, 0))
        self.btnStart.setMaximumSize(QtCore.QSize(126, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.gridLayout.addWidget(self.btnStart, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(HanZi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(126, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(126, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(HanZi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(126, 0))
        self.pushButton_6.setMaximumSize(QtCore.QSize(126, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(HanZi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(258, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(258, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(HanZi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 5, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(HanZi)
        self.pushButton_5.clicked.connect(HanZi.appendText)
        self.pushButton_6.clicked.connect(HanZi.removeText)
        QtCore.QMetaObject.connectSlotsByName(HanZi)

    def retranslateUi(self, HanZi):
        _translate = QtCore.QCoreApplication.translate
        HanZi.setWindowTitle(_translate("HanZi", "Form"))
        self.labPinYin.setText(_translate("HanZi", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">拼音</span></p></body></html>"))
        self.labGif.setText(_translate("HanZi", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">笔画</span></p><p align=\"center\"><span style=\" color:#aaaaff;\">演示</span></p></body></html>"))
        self.pushButton.setText(_translate("HanZi", "首页"))
        self.btnStart.setText(_translate("HanZi", "开始滚动"))
        self.pushButton_5.setText(_translate("HanZi", "添加"))
        self.pushButton_6.setText(_translate("HanZi", "删除"))
        self.lineEdit.setPlaceholderText(_translate("HanZi", "输入汉字"))
        self.checkBox.setText(_translate("HanZi", "开启/关闭语音"))
