# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Main.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(980, 700)
        Main.setMinimumSize(QtCore.QSize(980, 700))
        Main.setMaximumSize(QtCore.QSize(980, 700))
        Main.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Main.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widTitle = QtWidgets.QWidget(Main)
        self.widTitle.setGeometry(QtCore.QRect(0, 0, 980, 100))
        self.widTitle.setMinimumSize(QtCore.QSize(0, 100))
        self.widTitle.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widTitle.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.widTitle.setObjectName("widTitle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widTitle)
        self.horizontalLayout.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLogo = QtWidgets.QPushButton(self.widTitle)
        self.btnLogo.setMinimumSize(QtCore.QSize(138, 50))
        self.btnLogo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnLogo.setText("")
        self.btnLogo.setObjectName("btnLogo")
        self.horizontalLayout.addWidget(self.btnLogo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget_7 = QtWidgets.QWidget(self.widTitle)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_7)
        self.widget_4.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnUserpic = QtWidgets.QPushButton(self.widget_4)
        self.btnUserpic.setMinimumSize(QtCore.QSize(50, 50))
        self.btnUserpic.setMaximumSize(QtCore.QSize(50, 50))
        self.btnUserpic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUserpic.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnUserpic.setText("")
        self.btnUserpic.setObjectName("btnUserpic")
        self.horizontalLayout_2.addWidget(self.btnUserpic)
        self.btnCards = QtWidgets.QPushButton(self.widget_4)
        self.btnCards.setMinimumSize(QtCore.QSize(50, 50))
        self.btnCards.setMaximumSize(QtCore.QSize(50, 50))
        self.btnCards.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCards.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCards.setText("")
        self.btnCards.setObjectName("btnCards")
        self.horizontalLayout_2.addWidget(self.btnCards)
        self.btnChangeSkin = QtWidgets.QPushButton(self.widget_4)
        self.btnChangeSkin.setMinimumSize(QtCore.QSize(50, 50))
        self.btnChangeSkin.setMaximumSize(QtCore.QSize(50, 50))
        self.btnChangeSkin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnChangeSkin.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnChangeSkin.setText("")
        self.btnChangeSkin.setObjectName("btnChangeSkin")
        self.horizontalLayout_2.addWidget(self.btnChangeSkin)
        self.btnMini = QtWidgets.QPushButton(self.widget_4)
        self.btnMini.setMinimumSize(QtCore.QSize(50, 50))
        self.btnMini.setMaximumSize(QtCore.QSize(50, 50))
        self.btnMini.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMini.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnMini.setText("")
        self.btnMini.setObjectName("btnMini")
        self.horizontalLayout_2.addWidget(self.btnMini)
        self.btnClose = QtWidgets.QPushButton(self.widget_4)
        self.btnClose.setMinimumSize(QtCore.QSize(50, 50))
        self.btnClose.setMaximumSize(QtCore.QSize(50, 50))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnClose.setText("")
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnStore = QtWidgets.QPushButton(self.widget_8)
        self.btnStore.setMinimumSize(QtCore.QSize(40, 40))
        self.btnStore.setMaximumSize(QtCore.QSize(40, 40))
        self.btnStore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStore.setText("")
        self.btnStore.setObjectName("btnStore")
        self.horizontalLayout_4.addWidget(self.btnStore)
        self.labGoldPix = QtWidgets.QLabel(self.widget_8)
        self.labGoldPix.setMinimumSize(QtCore.QSize(40, 40))
        self.labGoldPix.setMaximumSize(QtCore.QSize(40, 40))
        self.labGoldPix.setText("")
        self.labGoldPix.setObjectName("labGoldPix")
        self.horizontalLayout_4.addWidget(self.labGoldPix)
        self.labGoldCount = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.labGoldCount.setFont(font)
        self.labGoldCount.setObjectName("labGoldCount")
        self.horizontalLayout_4.addWidget(self.labGoldCount)
        self.labJewelPix = QtWidgets.QLabel(self.widget_8)
        self.labJewelPix.setMinimumSize(QtCore.QSize(40, 40))
        self.labJewelPix.setMaximumSize(QtCore.QSize(40, 40))
        self.labJewelPix.setText("")
        self.labJewelPix.setObjectName("labJewelPix")
        self.horizontalLayout_4.addWidget(self.labJewelPix)
        self.labJewelCount = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.labJewelCount.setFont(font)
        self.labJewelCount.setObjectName("labJewelCount")
        self.horizontalLayout_4.addWidget(self.labJewelCount)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.horizontalLayout.addWidget(self.widget_7)
        self.widCenter = QtWidgets.QWidget(Main)
        self.widCenter.setGeometry(QtCore.QRect(0, 100, 980, 550))
        self.widCenter.setObjectName("widCenter")
        self.widChose = QtWidgets.QWidget(self.widCenter)
        self.widChose.setGeometry(QtCore.QRect(0, 170, 980, 370))
        self.widChose.setMinimumSize(QtCore.QSize(0, 370))
        self.widChose.setMaximumSize(QtCore.QSize(16777215, 370))
        self.widChose.setObjectName("widChose")
        self.gridLayout = QtWidgets.QGridLayout(self.widChose)
        self.gridLayout.setContentsMargins(50, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(60)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.btnGames = QtWidgets.QPushButton(self.widChose)
        self.btnGames.setMinimumSize(QtCore.QSize(163, 163))
        self.btnGames.setMaximumSize(QtCore.QSize(163, 163))
        self.btnGames.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGames.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnGames.setText("")
        self.btnGames.setObjectName("btnGames")
        self.gridLayout.addWidget(self.btnGames, 4, 1, 1, 1)
        self.btnMusics = QtWidgets.QPushButton(self.widChose)
        self.btnMusics.setMinimumSize(QtCore.QSize(163, 163))
        self.btnMusics.setMaximumSize(QtCore.QSize(163, 163))
        self.btnMusics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMusics.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMusics.setText("")
        self.btnMusics.setObjectName("btnMusics")
        self.gridLayout.addWidget(self.btnMusics, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widChose)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.btnMath = QtWidgets.QPushButton(self.widChose)
        self.btnMath.setMinimumSize(QtCore.QSize(163, 163))
        self.btnMath.setMaximumSize(QtCore.QSize(163, 163))
        self.btnMath.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMath.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMath.setText("")
        self.btnMath.setObjectName("btnMath")
        self.gridLayout.addWidget(self.btnMath, 2, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.widChose)
        self.line.setAutoFillBackground(False)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.widChose)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.btnEn = QtWidgets.QPushButton(self.widChose)
        self.btnEn.setMinimumSize(QtCore.QSize(163, 163))
        self.btnEn.setMaximumSize(QtCore.QSize(163, 163))
        self.btnEn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEn.setStyleSheet("qradialgradient:(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255))")
        self.btnEn.setText("")
        self.btnEn.setObjectName("btnEn")
        self.gridLayout.addWidget(self.btnEn, 2, 3, 1, 1)
        self.btnCn = QtWidgets.QPushButton(self.widChose)
        self.btnCn.setMinimumSize(QtCore.QSize(163, 163))
        self.btnCn.setMaximumSize(QtCore.QSize(163, 163))
        self.btnCn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCn.setStyleSheet("")
        self.btnCn.setText("")
        self.btnCn.setObjectName("btnCn")
        self.gridLayout.addWidget(self.btnCn, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.widChose)
        self.widget.setMinimumSize(QtCore.QSize(163, 163))
        self.widget.setMaximumSize(QtCore.QSize(163, 163))
        self.widget.setObjectName("widget")
        self.labMovies = QtWidgets.QLabel(self.widget)
        self.labMovies.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.labMovies.setText("")
        self.labMovies.setObjectName("labMovies")
        self.btnMovies = QtWidgets.QPushButton(self.widget)
        self.btnMovies.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.btnMovies.setMinimumSize(QtCore.QSize(163, 163))
        self.btnMovies.setMaximumSize(QtCore.QSize(163, 163))
        self.btnMovies.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMovies.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMovies.setText("")
        self.btnMovies.setObjectName("btnMovies")
        self.gridLayout.addWidget(self.widget, 4, 3, 1, 1)
        self.stkWid = QtWidgets.QStackedWidget(self.widCenter)
        self.stkWid.setGeometry(QtCore.QRect(0, 170, 980, 370))
        self.stkWid.setMinimumSize(QtCore.QSize(980, 370))
        self.stkWid.setMaximumSize(QtCore.QSize(16777215, 370))
        self.stkWid.setObjectName("stkWid")
        self.pageCn = QtWidgets.QWidget()
        self.pageCn.setObjectName("pageCn")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.pageCn)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnCn_HanZi = QtWidgets.QPushButton(self.pageCn)
        self.btnCn_HanZi.setMinimumSize(QtCore.QSize(163, 163))
        self.btnCn_HanZi.setMaximumSize(QtCore.QSize(163, 163))
        self.btnCn_HanZi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCn_HanZi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCn_HanZi.setStyleSheet("")
        self.btnCn_HanZi.setText("")
        self.btnCn_HanZi.setObjectName("btnCn_HanZi")
        self.horizontalLayout_8.addWidget(self.btnCn_HanZi)
        self.btnCn_PinYin = QtWidgets.QPushButton(self.pageCn)
        self.btnCn_PinYin.setMinimumSize(QtCore.QSize(163, 163))
        self.btnCn_PinYin.setMaximumSize(QtCore.QSize(163, 163))
        self.btnCn_PinYin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCn_PinYin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCn_PinYin.setText("")
        self.btnCn_PinYin.setObjectName("btnCn_PinYin")
        self.horizontalLayout_8.addWidget(self.btnCn_PinYin)
        self.btn111111 = QtWidgets.QPushButton(self.pageCn)
        self.btn111111.setMinimumSize(QtCore.QSize(163, 163))
        self.btn111111.setMaximumSize(QtCore.QSize(163, 163))
        self.btn111111.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn111111.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn111111.setStyleSheet("qradialgradient:(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255))")
        self.btn111111.setText("")
        self.btn111111.setObjectName("btn111111")
        self.horizontalLayout_8.addWidget(self.btn111111)
        self.stkWid.addWidget(self.pageCn)
        self.pageMath = QtWidgets.QWidget()
        self.pageMath.setObjectName("pageMath")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.pageMath)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnMath_PlusOrMinus100 = QtWidgets.QPushButton(self.pageMath)
        self.btnMath_PlusOrMinus100.setMinimumSize(QtCore.QSize(163, 163))
        self.btnMath_PlusOrMinus100.setMaximumSize(QtCore.QSize(163, 163))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(30)
        self.btnMath_PlusOrMinus100.setFont(font)
        self.btnMath_PlusOrMinus100.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMath_PlusOrMinus100.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMath_PlusOrMinus100.setStyleSheet("")
        self.btnMath_PlusOrMinus100.setObjectName("btnMath_PlusOrMinus100")
        self.horizontalLayout_7.addWidget(self.btnMath_PlusOrMinus100)
        self.pushButton_21 = QtWidgets.QPushButton(self.pageMath)
        self.pushButton_21.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_21.setMaximumSize(QtCore.QSize(163, 163))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(30)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_7.addWidget(self.pushButton_21)
        self.btn11111 = QtWidgets.QPushButton(self.pageMath)
        self.btn11111.setMinimumSize(QtCore.QSize(163, 163))
        self.btn11111.setMaximumSize(QtCore.QSize(163, 163))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.btn11111.setFont(font)
        self.btn11111.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn11111.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn11111.setStyleSheet("qradialgradient:(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255))")
        self.btn11111.setObjectName("btn11111")
        self.horizontalLayout_7.addWidget(self.btn11111)
        self.stkWid.addWidget(self.pageMath)
        self.pageEn = QtWidgets.QWidget()
        self.pageEn.setObjectName("pageEn")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.pageEn)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_17 = QtWidgets.QPushButton(self.pageEn)
        self.pushButton_17.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_17.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_17.setStyleSheet("")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_9.addWidget(self.pushButton_17)
        self.pushButton_16 = QtWidgets.QPushButton(self.pageEn)
        self.pushButton_16.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_16.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_9.addWidget(self.pushButton_16)
        self.pushButton_12 = QtWidgets.QPushButton(self.pageEn)
        self.pushButton_12.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_12.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_12.setStyleSheet("qradialgradient:(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255))")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_9.addWidget(self.pushButton_12)
        self.stkWid.addWidget(self.pageEn)
        self.pageGames = QtWidgets.QWidget()
        self.pageGames.setObjectName("pageGames")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pageGames)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.pageGames)
        self.widget_5.setMinimumSize(QtCore.QSize(163, 163))
        self.widget_5.setMaximumSize(QtCore.QSize(163, 163))
        self.widget_5.setObjectName("widget_5")
        self.btnGames_Guess = QtWidgets.QPushButton(self.widget_5)
        self.btnGames_Guess.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.btnGames_Guess.setMinimumSize(QtCore.QSize(163, 163))
        self.btnGames_Guess.setMaximumSize(QtCore.QSize(163, 163))
        self.btnGames_Guess.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGames_Guess.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnGames_Guess.setStyleSheet("")
        self.btnGames_Guess.setText("")
        self.btnGames_Guess.setObjectName("btnGames_Guess")
        self.labGames_Guess = QtWidgets.QLabel(self.widget_5)
        self.labGames_Guess.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.labGames_Guess.setMinimumSize(QtCore.QSize(163, 163))
        self.labGames_Guess.setMaximumSize(QtCore.QSize(163, 163))
        self.labGames_Guess.setText("")
        self.labGames_Guess.setScaledContents(True)
        self.labGames_Guess.setObjectName("labGames_Guess")
        self.labGames_Guess.raise_()
        self.btnGames_Guess.raise_()
        self.gridLayout_3.addWidget(self.widget_5, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.pageGames)
        self.widget_3.setMinimumSize(QtCore.QSize(163, 163))
        self.widget_3.setMaximumSize(QtCore.QSize(163, 163))
        self.widget_3.setObjectName("widget_3")
        self.btnGames_Rock = QtWidgets.QPushButton(self.widget_3)
        self.btnGames_Rock.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.btnGames_Rock.setMinimumSize(QtCore.QSize(163, 163))
        self.btnGames_Rock.setMaximumSize(QtCore.QSize(163, 163))
        self.btnGames_Rock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGames_Rock.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnGames_Rock.setStyleSheet("")
        self.btnGames_Rock.setText("")
        self.btnGames_Rock.setObjectName("btnGames_Rock")
        self.labGames_Rock = QtWidgets.QLabel(self.widget_3)
        self.labGames_Rock.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.labGames_Rock.setMinimumSize(QtCore.QSize(0, 0))
        self.labGames_Rock.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labGames_Rock.setText("")
        self.labGames_Rock.setObjectName("labGames_Rock")
        self.labGames_Rock.raise_()
        self.btnGames_Rock.raise_()
        self.gridLayout_3.addWidget(self.widget_3, 0, 0, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.pageGames)
        self.pushButton_24.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_24.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_24.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_24.setStyleSheet("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_3.addWidget(self.pushButton_24, 1, 2, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.pageGames)
        self.pushButton_25.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_25.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_25.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_25.setStyleSheet("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_3.addWidget(self.pushButton_25, 1, 4, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.pageGames)
        self.widget_6.setMinimumSize(QtCore.QSize(163, 163))
        self.widget_6.setMaximumSize(QtCore.QSize(163, 163))
        self.widget_6.setObjectName("widget_6")
        self.labGames_Puzzle = QtWidgets.QLabel(self.widget_6)
        self.labGames_Puzzle.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.labGames_Puzzle.setMinimumSize(QtCore.QSize(163, 163))
        self.labGames_Puzzle.setMaximumSize(QtCore.QSize(163, 163))
        self.labGames_Puzzle.setText("")
        self.labGames_Puzzle.setObjectName("labGames_Puzzle")
        self.btnGames_Puzzle = QtWidgets.QPushButton(self.widget_6)
        self.btnGames_Puzzle.setGeometry(QtCore.QRect(0, 0, 163, 163))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGames_Puzzle.sizePolicy().hasHeightForWidth())
        self.btnGames_Puzzle.setSizePolicy(sizePolicy)
        self.btnGames_Puzzle.setMinimumSize(QtCore.QSize(163, 163))
        self.btnGames_Puzzle.setMaximumSize(QtCore.QSize(163, 163))
        self.btnGames_Puzzle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGames_Puzzle.setText("")
        self.btnGames_Puzzle.setObjectName("btnGames_Puzzle")
        self.gridLayout_3.addWidget(self.widget_6, 0, 4, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.pageGames)
        self.widget_9.setObjectName("widget_9")
        self.labGames_CardMatching = QtWidgets.QLabel(self.widget_9)
        self.labGames_CardMatching.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.labGames_CardMatching.setMinimumSize(QtCore.QSize(163, 163))
        self.labGames_CardMatching.setMaximumSize(QtCore.QSize(163, 163))
        self.labGames_CardMatching.setText("")
        self.labGames_CardMatching.setObjectName("labGames_CardMatching")
        self.btnGames_CardMatching = QtWidgets.QPushButton(self.widget_9)
        self.btnGames_CardMatching.setGeometry(QtCore.QRect(0, 0, 163, 163))
        self.btnGames_CardMatching.setMinimumSize(QtCore.QSize(163, 163))
        self.btnGames_CardMatching.setMaximumSize(QtCore.QSize(163, 163))
        self.btnGames_CardMatching.setText("")
        self.btnGames_CardMatching.setObjectName("btnGames_CardMatching")
        self.gridLayout_3.addWidget(self.widget_9, 1, 0, 1, 1)
        self.stkWid.addWidget(self.pageGames)
        self.pageMusic = QtWidgets.QWidget()
        self.pageMusic.setObjectName("pageMusic")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pageMusic)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_26 = QtWidgets.QPushButton(self.pageMusic)
        self.pushButton_26.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_26.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_26.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_26.setStyleSheet("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_4.addWidget(self.pushButton_26, 0, 0, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.pageMusic)
        self.pushButton_27.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_27.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_27.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_27.setStyleSheet("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_4.addWidget(self.pushButton_27, 0, 1, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.pageMusic)
        self.pushButton_28.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_28.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_28.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_28.setStyleSheet("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_4.addWidget(self.pushButton_28, 0, 2, 1, 1)
        self.stkWid.addWidget(self.pageMusic)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_29 = QtWidgets.QPushButton(self.page)
        self.pushButton_29.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_29.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_29.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_29.setStyleSheet("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_5.addWidget(self.pushButton_29, 0, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.page)
        self.pushButton_30.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_30.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_30.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_30.setStyleSheet("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_5.addWidget(self.pushButton_30, 0, 1, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.page)
        self.pushButton_31.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_31.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_31.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_31.setStyleSheet("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_5.addWidget(self.pushButton_31, 0, 2, 1, 1)
        self.stkWid.addWidget(self.page)
        self.widBack = QtWidgets.QWidget(self.widCenter)
        self.widBack.setGeometry(QtCore.QRect(0, 0, 980, 30))
        self.widBack.setMinimumSize(QtCore.QSize(0, 30))
        self.widBack.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widBack.setObjectName("widBack")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widBack)
        self.horizontalLayout_5.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.widBack)
        self.widget_2.setMinimumSize(QtCore.QSize(75, 26))
        self.widget_2.setMaximumSize(QtCore.QSize(75, 26))
        self.widget_2.setObjectName("widget_2")
        self.labBackLeft = QtWidgets.QLabel(self.widget_2)
        self.labBackLeft.setGeometry(QtCore.QRect(0, 0, 20, 26))
        self.labBackLeft.setMinimumSize(QtCore.QSize(20, 26))
        self.labBackLeft.setMaximumSize(QtCore.QSize(20, 26))
        self.labBackLeft.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labBackLeft.setText("")
        self.labBackLeft.setObjectName("labBackLeft")
        self.labBackRight = QtWidgets.QLabel(self.widget_2)
        self.labBackRight.setGeometry(QtCore.QRect(20, 0, 55, 26))
        self.labBackRight.setMinimumSize(QtCore.QSize(55, 26))
        self.labBackRight.setMaximumSize(QtCore.QSize(55, 26))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        self.labBackRight.setFont(font)
        self.labBackRight.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labBackRight.setAlignment(QtCore.Qt.AlignCenter)
        self.labBackRight.setObjectName("labBackRight")
        self.btnBack = QtWidgets.QPushButton(self.widget_2)
        self.btnBack.setGeometry(QtCore.QRect(0, 0, 75, 26))
        self.btnBack.setMinimumSize(QtCore.QSize(75, 26))
        self.btnBack.setMaximumSize(QtCore.QSize(75, 26))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnBack.setFont(font)
        self.btnBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBack.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnBack.setText("")
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.labBackLink = QtWidgets.QLabel(self.widBack)
        self.labBackLink.setMinimumSize(QtCore.QSize(600, 0))
        self.labBackLink.setOpenExternalLinks(False)
        self.labBackLink.setObjectName("labBackLink")
        self.horizontalLayout_5.addWidget(self.labBackLink)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btnMenu = QtWidgets.QPushButton(self.widBack)
        self.btnMenu.setMinimumSize(QtCore.QSize(120, 0))
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout_5.addWidget(self.btnMenu)
        self.widWelcome = QtWidgets.QWidget(self.widCenter)
        self.widWelcome.setGeometry(QtCore.QRect(0, 0, 980, 170))
        self.widWelcome.setMinimumSize(QtCore.QSize(0, 0))
        self.widWelcome.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widWelcome.setObjectName("widWelcome")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widWelcome)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labWelcome = QtWidgets.QLabel(self.widWelcome)
        self.labWelcome.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.labWelcome.setText("")
        self.labWelcome.setScaledContents(True)
        self.labWelcome.setAlignment(QtCore.Qt.AlignCenter)
        self.labWelcome.setObjectName("labWelcome")
        self.horizontalLayout_6.addWidget(self.labWelcome)
        self.widHello = QtWidgets.QWidget(self.widCenter)
        self.widHello.setGeometry(QtCore.QRect(0, 30, 980, 110))
        self.widHello.setObjectName("widHello")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widHello)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labHello = QtWidgets.QLabel(self.widHello)
        self.labHello.setAlignment(QtCore.Qt.AlignCenter)
        self.labHello.setObjectName("labHello")
        self.horizontalLayout_10.addWidget(self.labHello)
        self.stkWid.raise_()
        self.widChose.raise_()
        self.widWelcome.raise_()
        self.widHello.raise_()
        self.widBack.raise_()
        self.labMainBackground = QtWidgets.QLabel(Main)
        self.labMainBackground.setGeometry(QtCore.QRect(0, 0, 980, 700))
        self.labMainBackground.setText("")
        self.labMainBackground.setScaledContents(True)
        self.labMainBackground.setObjectName("labMainBackground")
        self.widStatusTip = QtWidgets.QWidget(Main)
        self.widStatusTip.setGeometry(QtCore.QRect(0, 650, 970, 50))
        self.widStatusTip.setObjectName("widStatusTip")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widStatusTip)
        self.horizontalLayout_3.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labStatusTip = QtWidgets.QLabel(self.widStatusTip)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labStatusTip.setFont(font)
        self.labStatusTip.setText("")
        self.labStatusTip.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labStatusTip.setObjectName("labStatusTip")
        self.horizontalLayout_3.addWidget(self.labStatusTip)
        self.btnStatusTip = QtWidgets.QPushButton(self.widStatusTip)
        self.btnStatusTip.setMaximumSize(QtCore.QSize(30, 30))
        self.btnStatusTip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStatusTip.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnStatusTip.setText("")
        self.btnStatusTip.setObjectName("btnStatusTip")
        self.horizontalLayout_3.addWidget(self.btnStatusTip)
        self.btnStatusTipChange = QtWidgets.QPushButton(Main)
        self.btnStatusTipChange.setGeometry(QtCore.QRect(970, 650, 10, 50))
        self.btnStatusTipChange.setText("")
        self.btnStatusTipChange.setObjectName("btnStatusTipChange")
        self.widMenu = QtWidgets.QWidget(Main)
        self.widMenu.setGeometry(QtCore.QRect(700, 130, 280, 220))
        self.widMenu.setObjectName("widMenu")
        self.tabWidget = QtWidgets.QTabWidget(self.widMenu)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 280, 220))
        self.tabWidget.setMinimumSize(QtCore.QSize(280, 220))
        self.tabWidget.setMaximumSize(QtCore.QSize(280, 220))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnClear = QtWidgets.QPushButton(self.tab)
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout.addWidget(self.btnClear)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWid = QtWidgets.QWidget()
        self.scrollAreaWid.setGeometry(QtCore.QRect(0, 0, 274, 164))
        self.scrollAreaWid.setObjectName("scrollAreaWid")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWid)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWid)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout.setStretch(1, 9)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(40, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(70, 80, 104, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.lineEditSearch = QtWidgets.QLineEdit(self.widMenu)
        self.lineEditSearch.setGeometry(QtCore.QRect(162, 0, 116, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setText("")
        self.lineEditSearch.setMaxLength(15)
        self.lineEditSearch.setFrame(True)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.labMainBackground.raise_()
        self.widTitle.raise_()
        self.widCenter.raise_()
        self.widStatusTip.raise_()
        self.btnStatusTipChange.raise_()
        self.widMenu.raise_()

        self.retranslateUi(Main)
        self.stkWid.setCurrentIndex(5)
        self.tabWidget.setCurrentIndex(0)
        self.btnMini.clicked.connect(Main.showMinimized)
        self.btnClose.clicked.connect(Main.close)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.labGoldCount.setText(_translate("Main", "0"))
        self.labJewelCount.setText(_translate("Main", "0"))
        self.label_2.setText(_translate("Main", "<html><head/><body><p>学</p><p>习</p></body></html>"))
        self.label_3.setText(_translate("Main", "<html><head/><body><p>娱</p><p>乐</p></body></html>"))
        self.btnMath_PlusOrMinus100.setText(_translate("Main", "100以内\n"
"加减法"))
        self.btn11111.setText(_translate("Main", "数学"))
        self.pushButton_16.setText(_translate("Main", "英语"))
        self.pushButton_24.setText(_translate("Main", "game"))
        self.pushButton_25.setText(_translate("Main", "game"))
        self.pushButton_26.setText(_translate("Main", "Music"))
        self.pushButton_27.setText(_translate("Main", "Music"))
        self.pushButton_28.setText(_translate("Main", "Music"))
        self.pushButton_29.setText(_translate("Main", "movies"))
        self.pushButton_30.setText(_translate("Main", "movies"))
        self.pushButton_31.setText(_translate("Main", "movies"))
        self.labBackRight.setText(_translate("Main", "返回"))
        self.labBackLink.setText(_translate("Main", "首页>"))
        self.btnMenu.setText(_translate("Main", "课程选择"))
        self.labHello.setText(_translate("Main", "Hi,XXX!"))
        self.btnClear.setText(_translate("Main", "×"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Main", "默认课程"))
        self.lineEdit.setText(_translate("Main", "的的"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Main", "自定义课程"))


