# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Cn_PinYin.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Cn_PinYin(object):
    def setupUi(self, Cn_PinYin):
        Cn_PinYin.setObjectName("Cn_PinYin")
        Cn_PinYin.resize(980, 520)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(9)
        Cn_PinYin.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Cn_PinYin)
        self.verticalLayout_3.setContentsMargins(40, 0, 40, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(Cn_PinYin)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 35))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widInput = QtWidgets.QWidget(Cn_PinYin)
        self.widInput.setMinimumSize(QtCore.QSize(0, 126))
        self.widInput.setMaximumSize(QtCore.QSize(16777215, 126))
        self.widInput.setObjectName("widInput")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widInput)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEditUp = QtWidgets.QTextEdit(self.widInput)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(40)
        self.textEditUp.setFont(font)
        self.textEditUp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEditUp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditUp.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditUp.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEditUp.setObjectName("textEditUp")
        self.verticalLayout.addWidget(self.textEditUp)
        self.textEditDn = QtWidgets.QTextEdit(self.widInput)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(40)
        self.textEditDn.setFont(font)
        self.textEditDn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEditDn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditDn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditDn.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEditDn.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEditDn.setObjectName("textEditDn")
        self.verticalLayout.addWidget(self.textEditDn)
        self.textEditDn.raise_()
        self.textEditUp.raise_()
        self.verticalLayout_3.addWidget(self.widInput)
        self.widget_3 = QtWidgets.QWidget(Cn_PinYin)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setMinimumSize(QtCore.QSize(0, 35))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit.setGeometry(QtCore.QRect(130, 90, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_6 = QtWidgets.QWidget(Cn_PinYin)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 35))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.widTimeShow = QtWidgets.QWidget(self.widget_6)
        self.widTimeShow.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.widTimeShow.setFont(font)
        self.widTimeShow.setObjectName("widTimeShow")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widTimeShow)
        self.horizontalLayout.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labTimePic = QtWidgets.QLabel(self.widTimeShow)
        self.labTimePic.setMinimumSize(QtCore.QSize(35, 0))
        self.labTimePic.setText("")
        self.labTimePic.setAlignment(QtCore.Qt.AlignCenter)
        self.labTimePic.setObjectName("labTimePic")
        self.horizontalLayout.addWidget(self.labTimePic)
        self.label = QtWidgets.QLabel(self.widTimeShow)
        self.label.setMinimumSize(QtCore.QSize(26, 35))
        self.label.setMaximumSize(QtCore.QSize(26, 35))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labTime = QtWidgets.QLabel(self.widTimeShow)
        self.labTime.setMinimumSize(QtCore.QSize(54, 35))
        self.labTime.setMaximumSize(QtCore.QSize(54, 35))
        self.labTime.setStyleSheet("color: rgb(236, 94, 0);")
        self.labTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labTime.setObjectName("labTime")
        self.horizontalLayout.addWidget(self.labTime)
        self.labSpeedPic = QtWidgets.QLabel(self.widTimeShow)
        self.labSpeedPic.setMinimumSize(QtCore.QSize(35, 0))
        self.labSpeedPic.setText("")
        self.labSpeedPic.setAlignment(QtCore.Qt.AlignCenter)
        self.labSpeedPic.setObjectName("labSpeedPic")
        self.horizontalLayout.addWidget(self.labSpeedPic)
        self.label_5 = QtWidgets.QLabel(self.widTimeShow)
        self.label_5.setMinimumSize(QtCore.QSize(26, 35))
        self.label_5.setMaximumSize(QtCore.QSize(26, 35))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.labSpeed = QtWidgets.QLabel(self.widTimeShow)
        self.labSpeed.setMinimumSize(QtCore.QSize(64, 35))
        self.labSpeed.setMaximumSize(QtCore.QSize(64, 35))
        self.labSpeed.setStyleSheet("color: rgb(236, 94, 0);")
        self.labSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labSpeed.setObjectName("labSpeed")
        self.horizontalLayout.addWidget(self.labSpeed)
        self.labProgressPic = QtWidgets.QLabel(self.widTimeShow)
        self.labProgressPic.setMinimumSize(QtCore.QSize(35, 0))
        self.labProgressPic.setText("")
        self.labProgressPic.setAlignment(QtCore.Qt.AlignCenter)
        self.labProgressPic.setObjectName("labProgressPic")
        self.horizontalLayout.addWidget(self.labProgressPic)
        self.label_8 = QtWidgets.QLabel(self.widTimeShow)
        self.label_8.setMinimumSize(QtCore.QSize(26, 35))
        self.label_8.setMaximumSize(QtCore.QSize(26, 35))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.labProgress = QtWidgets.QLabel(self.widTimeShow)
        self.labProgress.setMinimumSize(QtCore.QSize(36, 35))
        self.labProgress.setMaximumSize(QtCore.QSize(36, 35))
        self.labProgress.setStyleSheet("color: rgb(236, 94, 0);")
        self.labProgress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labProgress.setObjectName("labProgress")
        self.horizontalLayout.addWidget(self.labProgress)
        self.labAccuracyPic = QtWidgets.QLabel(self.widTimeShow)
        self.labAccuracyPic.setMinimumSize(QtCore.QSize(35, 0))
        self.labAccuracyPic.setText("")
        self.labAccuracyPic.setAlignment(QtCore.Qt.AlignCenter)
        self.labAccuracyPic.setObjectName("labAccuracyPic")
        self.horizontalLayout.addWidget(self.labAccuracyPic)
        self.label_11 = QtWidgets.QLabel(self.widTimeShow)
        self.label_11.setMinimumSize(QtCore.QSize(39, 35))
        self.label_11.setMaximumSize(QtCore.QSize(39, 35))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.labAccuracy = QtWidgets.QLabel(self.widTimeShow)
        self.labAccuracy.setMinimumSize(QtCore.QSize(36, 35))
        self.labAccuracy.setMaximumSize(QtCore.QSize(36, 35))
        self.labAccuracy.setStyleSheet("color: rgb(236, 94, 0);")
        self.labAccuracy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labAccuracy.setObjectName("labAccuracy")
        self.horizontalLayout.addWidget(self.labAccuracy)
        self.horizontalLayout_3.addWidget(self.widTimeShow)
        self.wid = QtWidgets.QWidget(self.widget_6)
        self.wid.setMinimumSize(QtCore.QSize(0, 35))
        self.wid.setObjectName("wid")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wid)
        self.horizontalLayout_4.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnTimeUpdate = QtWidgets.QPushButton(self.wid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTimeUpdate.sizePolicy().hasHeightForWidth())
        self.btnTimeUpdate.setSizePolicy(sizePolicy)
        self.btnTimeUpdate.setMinimumSize(QtCore.QSize(35, 35))
        self.btnTimeUpdate.setMaximumSize(QtCore.QSize(35, 35))
        self.btnTimeUpdate.setText("")
        self.btnTimeUpdate.setObjectName("btnTimeUpdate")
        self.horizontalLayout_4.addWidget(self.btnTimeUpdate)
        self.btnTimeStart = QtWidgets.QPushButton(self.wid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTimeStart.sizePolicy().hasHeightForWidth())
        self.btnTimeStart.setSizePolicy(sizePolicy)
        self.btnTimeStart.setMinimumSize(QtCore.QSize(35, 35))
        self.btnTimeStart.setMaximumSize(QtCore.QSize(35, 35))
        self.btnTimeStart.setText("")
        self.btnTimeStart.setObjectName("btnTimeStart")
        self.horizontalLayout_4.addWidget(self.btnTimeStart)
        self.horizontalLayout_3.addWidget(self.wid)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.widget_6)

        self.retranslateUi(Cn_PinYin)
        QtCore.QMetaObject.connectSlotsByName(Cn_PinYin)

    def retranslateUi(self, Cn_PinYin):
        _translate = QtCore.QCoreApplication.translate
        Cn_PinYin.setWindowTitle(_translate("Cn_PinYin", "Form"))
        self.checkBox.setText(_translate("Cn_PinYin", "限时"))
        self.label_14.setText(_translate("Cn_PinYin", "分钟"))
        self.textEditUp.setHtml(_translate("Cn_PinYin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'新宋体\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt;\"><br /></p></body></html>"))
        self.textEditDn.setHtml(_translate("Cn_PinYin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'新宋体\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_13.setText(_translate("Cn_PinYin", "<html><head/><body><p><span style=\" font-size:14pt;\">TextLabel yingyuang</span></p></body></html>"))
        self.label.setText(_translate("Cn_PinYin", "时间"))
        self.labTime.setText(_translate("Cn_PinYin", "59:59:59"))
        self.label_5.setText(_translate("Cn_PinYin", "速度"))
        self.labSpeed.setText(_translate("Cn_PinYin", "9999字/分"))
        self.label_8.setText(_translate("Cn_PinYin", "进度"))
        self.labProgress.setText(_translate("Cn_PinYin", "100%"))
        self.label_11.setText(_translate("Cn_PinYin", "正确率"))
        self.labAccuracy.setText(_translate("Cn_PinYin", "100%"))

