# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Games_Rock.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Games_Rock(object):
    def setupUi(self, Games_Rock):
        Games_Rock.setObjectName("Games_Rock")
        Games_Rock.resize(980, 522)
        self.verticalLayout = QtWidgets.QVBoxLayout(Games_Rock)
        self.verticalLayout.setContentsMargins(0, 150, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Games_Rock)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 312))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 312))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widLab = QtWidgets.QWidget(self.widget_2)
        self.widLab.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widLab.setObjectName("widLab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widLab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labRock = QtWidgets.QLabel(self.widLab)
        self.labRock.setMinimumSize(QtCore.QSize(100, 100))
        self.labRock.setMaximumSize(QtCore.QSize(100, 100))
        self.labRock.setText("")
        self.labRock.setAlignment(QtCore.Qt.AlignCenter)
        self.labRock.setObjectName("labRock")
        self.verticalLayout_2.addWidget(self.labRock)
        self.labScissor = QtWidgets.QLabel(self.widLab)
        self.labScissor.setMinimumSize(QtCore.QSize(100, 100))
        self.labScissor.setMaximumSize(QtCore.QSize(100, 100))
        self.labScissor.setText("")
        self.labScissor.setAlignment(QtCore.Qt.AlignCenter)
        self.labScissor.setObjectName("labScissor")
        self.verticalLayout_2.addWidget(self.labScissor)
        self.labPaper = QtWidgets.QLabel(self.widLab)
        self.labPaper.setMinimumSize(QtCore.QSize(100, 100))
        self.labPaper.setMaximumSize(QtCore.QSize(100, 100))
        self.labPaper.setText("")
        self.labPaper.setAlignment(QtCore.Qt.AlignCenter)
        self.labPaper.setObjectName("labPaper")
        self.verticalLayout_2.addWidget(self.labPaper)
        self.horizontalLayout_2.addWidget(self.widLab)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(291, 291))
        self.widget_3.setObjectName("widget_3")
        self.labMovie = QtWidgets.QLabel(self.widget_3)
        self.labMovie.setGeometry(QtCore.QRect(0, 0, 291, 291))
        self.labMovie.setMinimumSize(QtCore.QSize(291, 291))
        self.labMovie.setMaximumSize(QtCore.QSize(291, 291))
        self.labMovie.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labMovie.setText("")
        self.labMovie.setAlignment(QtCore.Qt.AlignCenter)
        self.labMovie.setObjectName("labMovie")
        self.btnPk = QtWidgets.QPushButton(self.widget_3)
        self.btnPk.setGeometry(QtCore.QRect(95, 95, 100, 100))
        self.btnPk.setMinimumSize(QtCore.QSize(100, 100))
        self.btnPk.setMaximumSize(QtCore.QSize(100, 100))
        self.btnPk.setText("")
        self.btnPk.setObjectName("btnPk")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widBtn = QtWidgets.QWidget(self.widget_2)
        self.widBtn.setObjectName("widBtn")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widBtn)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnRock = QtWidgets.QPushButton(self.widBtn)
        self.btnRock.setMinimumSize(QtCore.QSize(100, 100))
        self.btnRock.setMaximumSize(QtCore.QSize(100, 100))
        self.btnRock.setText("")
        self.btnRock.setObjectName("btnRock")
        self.verticalLayout_3.addWidget(self.btnRock)
        self.btnScissor = QtWidgets.QPushButton(self.widBtn)
        self.btnScissor.setMinimumSize(QtCore.QSize(100, 100))
        self.btnScissor.setMaximumSize(QtCore.QSize(100, 100))
        self.btnScissor.setText("")
        self.btnScissor.setObjectName("btnScissor")
        self.verticalLayout_3.addWidget(self.btnScissor)
        self.btnPaper = QtWidgets.QPushButton(self.widBtn)
        self.btnPaper.setMinimumSize(QtCore.QSize(100, 100))
        self.btnPaper.setMaximumSize(QtCore.QSize(100, 100))
        self.btnPaper.setText("")
        self.btnPaper.setObjectName("btnPaper")
        self.verticalLayout_3.addWidget(self.btnPaper)
        self.horizontalLayout_2.addWidget(self.widBtn)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Games_Rock)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labWin = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labWin.setFont(font)
        self.labWin.setObjectName("labWin")
        self.horizontalLayout.addWidget(self.labWin)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.labLose = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labLose.setFont(font)
        self.labLose.setObjectName("labLose")
        self.horizontalLayout.addWidget(self.labLose)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.labDraw = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labDraw.setFont(font)
        self.labDraw.setObjectName("labDraw")
        self.horizontalLayout.addWidget(self.labDraw)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Games_Rock)
        QtCore.QMetaObject.connectSlotsByName(Games_Rock)

    def retranslateUi(self, Games_Rock):
        _translate = QtCore.QCoreApplication.translate
        Games_Rock.setWindowTitle(_translate("Games_Rock", "Form"))
        self.label.setText(_translate("Games_Rock", "胜利："))
        self.labWin.setText(_translate("Games_Rock", "0"))
        self.label_2.setText(_translate("Games_Rock", "失败："))
        self.labLose.setText(_translate("Games_Rock", "0"))
        self.label_3.setText(_translate("Games_Rock", "平局："))
        self.labDraw.setText(_translate("Games_Rock", "0"))


