# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyBoard.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 110)
        Form.setMinimumSize(QtCore.QSize(400, 110))
        Form.setMaximumSize(QtCore.QSize(400, 110))
        font = QtGui.QFont()
        font.setPointSize(9)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.widget_2 = KeyboardBtn(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_2.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_2.setFont(font)
        self.widget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_22.addWidget(self.widget_2)
        self.widget = KeyboardBtn(Form)
        self.widget.setMinimumSize(QtCore.QSize(25, 25))
        self.widget.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget.setFont(font)
        self.widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout_22.addWidget(self.widget)
        self.widget_4 = KeyboardBtn(Form)
        self.widget_4.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_4.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_4.setFont(font)
        self.widget_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_7.setFont(font)
        self.label_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_8.setFont(font)
        self.label_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_22.addWidget(self.widget_4)
        self.widget_5 = KeyboardBtn(Form)
        self.widget_5.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_5.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_5.setFont(font)
        self.widget_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_9.setFont(font)
        self.label_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget_5)
        self.label_10.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_10.setFont(font)
        self.label_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.horizontalLayout_22.addWidget(self.widget_5)
        self.widget_6 = KeyboardBtn(Form)
        self.widget_6.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_6.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_6.setFont(font)
        self.widget_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_11.setFont(font)
        self.label_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget_6)
        self.label_12.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_12.setFont(font)
        self.label_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.horizontalLayout_22.addWidget(self.widget_6)
        self.widget_7 = KeyboardBtn(Form)
        self.widget_7.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_7.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_7.setFont(font)
        self.widget_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_13.setFont(font)
        self.label_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_7)
        self.label_14.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_14.setFont(font)
        self.label_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.horizontalLayout_22.addWidget(self.widget_7)
        self.widget_8 = KeyboardBtn(Form)
        self.widget_8.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_8.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_8.setFont(font)
        self.widget_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_15.setFont(font)
        self.label_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.widget_8)
        self.label_16.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_16.setFont(font)
        self.label_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.horizontalLayout_22.addWidget(self.widget_8)
        self.widget_9 = KeyboardBtn(Form)
        self.widget_9.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_9.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_9.setFont(font)
        self.widget_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_9.setStyleSheet("")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_17.setFont(font)
        self.label_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget_9)
        self.label_18.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_18.setFont(font)
        self.label_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_18.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.horizontalLayout_22.addWidget(self.widget_9)
        self.widget_10 = KeyboardBtn(Form)
        self.widget_10.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_10.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_10.setFont(font)
        self.widget_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_10.setStyleSheet("")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_19.setFont(font)
        self.label_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.widget_10)
        self.label_20.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_20.setFont(font)
        self.label_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_20.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.horizontalLayout_22.addWidget(self.widget_10)
        self.widget_11 = KeyboardBtn(Form)
        self.widget_11.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_11.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_11.setFont(font)
        self.widget_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_21.setFont(font)
        self.label_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.widget_11)
        self.label_22.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_22.setFont(font)
        self.label_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_22.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.horizontalLayout_22.addWidget(self.widget_11)
        self.widget_12 = KeyboardBtn(Form)
        self.widget_12.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_12.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_12.setFont(font)
        self.widget_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_12.setStyleSheet("")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_23.setFont(font)
        self.label_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.widget_12)
        self.label_24.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_24.setFont(font)
        self.label_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        self.horizontalLayout_22.addWidget(self.widget_12)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_22.addWidget(self.pushButton)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMinimumSize(QtCore.QSize(13, 25))
        self.widget_3.setMaximumSize(QtCore.QSize(13, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_3.setFont(font)
        self.widget_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.btnClose = QtWidgets.QPushButton(self.widget_3)
        self.btnClose.setMinimumSize(QtCore.QSize(13, 13))
        self.btnClose.setMaximumSize(QtCore.QSize(13, 13))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btnClose.setFont(font)
        self.btnClose.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClose.setFlat(False)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_26.addWidget(self.btnClose, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.horizontalLayout_22.addWidget(self.widget_3)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setMinimumSize(QtCore.QSize(60, 25))
        self.pushButton_3.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.widget_13 = KeyboardBtn(Form)
        self.widget_13.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_13.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_13.setFont(font)
        self.widget_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_25.setFont(font)
        self.label_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.widget_13)
        self.label_26.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_26.setFont(font)
        self.label_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_26.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.horizontalLayout_3.addWidget(self.widget_13)
        self.widget_14 = KeyboardBtn(Form)
        self.widget_14.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_14.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_14.setFont(font)
        self.widget_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_27 = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_27.setFont(font)
        self.label_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_14.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.widget_14)
        self.label_28.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_28.setFont(font)
        self.label_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_28.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        self.horizontalLayout_3.addWidget(self.widget_14)
        self.widget_15 = KeyboardBtn(Form)
        self.widget_15.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_15.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_15.setFont(font)
        self.widget_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_29 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_29.setFont(font)
        self.label_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_15.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.widget_15)
        self.label_30.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_30.setFont(font)
        self.label_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_30.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        self.horizontalLayout_3.addWidget(self.widget_15)
        self.widget_16 = KeyboardBtn(Form)
        self.widget_16.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_16.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_16.setFont(font)
        self.widget_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_31 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_31.setFont(font)
        self.label_31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_16.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.widget_16)
        self.label_32.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_32.setFont(font)
        self.label_32.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_32.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_16.addWidget(self.label_32)
        self.horizontalLayout_3.addWidget(self.widget_16)
        self.widget_22 = KeyboardBtn(Form)
        self.widget_22.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_22.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_22.setFont(font)
        self.widget_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_43 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_43.setFont(font)
        self.label_43.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_25.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.widget_22)
        self.label_44.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_44.setFont(font)
        self.label_44.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_44.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_25.addWidget(self.label_44)
        self.horizontalLayout_3.addWidget(self.widget_22)
        self.widget_17 = KeyboardBtn(Form)
        self.widget_17.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_17.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_17.setFont(font)
        self.widget_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_33 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_33.setFont(font)
        self.label_33.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_17.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.widget_17)
        self.label_34.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_34.setFont(font)
        self.label_34.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_34.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_17.addWidget(self.label_34)
        self.horizontalLayout_3.addWidget(self.widget_17)
        self.widget_18 = KeyboardBtn(Form)
        self.widget_18.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_18.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_18.setFont(font)
        self.widget_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_35 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_35.setFont(font)
        self.label_35.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_18.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.widget_18)
        self.label_36.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_36.setFont(font)
        self.label_36.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_36.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_18.addWidget(self.label_36)
        self.horizontalLayout_3.addWidget(self.widget_18)
        self.widget_19 = KeyboardBtn(Form)
        self.widget_19.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_19.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_19.setFont(font)
        self.widget_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_37 = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_37.setFont(font)
        self.label_37.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_19.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.widget_19)
        self.label_38.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_38.setFont(font)
        self.label_38.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_38.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_19.addWidget(self.label_38)
        self.horizontalLayout_3.addWidget(self.widget_19)
        self.widget_20 = KeyboardBtn(Form)
        self.widget_20.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_20.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_20.setFont(font)
        self.widget_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_39 = QtWidgets.QLabel(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_39.setFont(font)
        self.label_39.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_20.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.widget_20)
        self.label_40.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_40.setFont(font)
        self.label_40.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_40.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_20.addWidget(self.label_40)
        self.horizontalLayout_3.addWidget(self.widget_20)
        self.widget_21 = KeyboardBtn(Form)
        self.widget_21.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_21.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.widget_21.setFont(font)
        self.widget_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_41 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_41.setFont(font)
        self.label_41.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_21.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.widget_21)
        self.label_42.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.label_42.setFont(font)
        self.label_42.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_42.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_21.addWidget(self.label_42)
        self.horizontalLayout_3.addWidget(self.widget_21)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 25))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_5.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_23.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_6.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_23.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_7.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_23.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_8.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_8.setFont(font)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_23.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_9.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_9.setFont(font)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_23.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_10.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_10.setFont(font)
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_23.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_11.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_11.setFont(font)
        self.pushButton_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_23.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_12.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_12.setFont(font)
        self.pushButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_12.setFlat(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_23.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_13.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_13.setFont(font)
        self.pushButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_23.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_14.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_14.setFont(font)
        self.pushButton_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_14.setFlat(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_23.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_15.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_15.setFont(font)
        self.pushButton_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_15.setFlat(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_23.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_16.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_16.setFont(font)
        self.pushButton_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_16.setFlat(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_23.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_17.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_17.setFont(font)
        self.pushButton_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_17.setFlat(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_23.addWidget(self.pushButton_17)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_27 = QtWidgets.QPushButton(Form)
        self.pushButton_27.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_27.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_27.setFont(font)
        self.pushButton_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_27.setFlat(False)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_24.addWidget(self.pushButton_27)
        self.pushButton_22 = QtWidgets.QPushButton(Form)
        self.pushButton_22.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_22.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_22.setFont(font)
        self.pushButton_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_22.setFlat(False)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_24.addWidget(self.pushButton_22)
        self.pushButton_28 = QtWidgets.QPushButton(Form)
        self.pushButton_28.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_28.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_28.setFont(font)
        self.pushButton_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_28.setFlat(False)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_24.addWidget(self.pushButton_28)
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_19.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_19.setFont(font)
        self.pushButton_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_19.setFlat(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_24.addWidget(self.pushButton_19)
        self.pushButton_26 = QtWidgets.QPushButton(Form)
        self.pushButton_26.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_26.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_26.setFont(font)
        self.pushButton_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_26.setFlat(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_24.addWidget(self.pushButton_26)
        self.pushButton_29 = QtWidgets.QPushButton(Form)
        self.pushButton_29.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_29.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_29.setFont(font)
        self.pushButton_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_29.setFlat(False)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_24.addWidget(self.pushButton_29)
        self.pushButton_23 = QtWidgets.QPushButton(Form)
        self.pushButton_23.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_23.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_23.setFont(font)
        self.pushButton_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_23.setFlat(False)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_24.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(Form)
        self.pushButton_24.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_24.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_24.setFont(font)
        self.pushButton_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_24.setFlat(False)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_24.addWidget(self.pushButton_24)
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_18.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_18.setFont(font)
        self.pushButton_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_18.setFlat(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_24.addWidget(self.pushButton_18)
        self.pushButton_30 = QtWidgets.QPushButton(Form)
        self.pushButton_30.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_30.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_30.setFont(font)
        self.pushButton_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_30.setFlat(False)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_24.addWidget(self.pushButton_30)
        self.pushButton_25 = QtWidgets.QPushButton(Form)
        self.pushButton_25.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_25.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_25.setFont(font)
        self.pushButton_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_25.setFlat(False)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_24.addWidget(self.pushButton_25)
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_20.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_20.setFont(font)
        self.pushButton_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_20.setFlat(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_24.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_21.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        self.pushButton_21.setFont(font)
        self.pushButton_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_21.setFlat(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_24.addWidget(self.pushButton_21)
        self.verticalLayout.addLayout(self.horizontalLayout_24)

        self.retranslateUi(Form)
        self.btnClose.clicked.connect(Form.close)
        self.pushButton.clicked.connect(Form.delPreStr)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.widget_2.setProperty("state", _translate("Form", "symbol"))
        self.label_3.setText(_translate("Form", "`"))
        self.label_4.setText(_translate("Form", "~"))
        self.widget.setProperty("state", _translate("Form", "symbol"))
        self.label.setText(_translate("Form", "1"))
        self.label_2.setText(_translate("Form", "!"))
        self.widget_4.setProperty("state", _translate("Form", "symbol"))
        self.label_7.setText(_translate("Form", "2"))
        self.label_8.setText(_translate("Form", "@"))
        self.widget_5.setProperty("state", _translate("Form", "symbol"))
        self.label_9.setText(_translate("Form", "3"))
        self.label_10.setText(_translate("Form", "#"))
        self.widget_6.setProperty("state", _translate("Form", "symbol"))
        self.label_11.setText(_translate("Form", "4"))
        self.label_12.setText(_translate("Form", "$"))
        self.widget_7.setProperty("state", _translate("Form", "symbol"))
        self.label_13.setText(_translate("Form", "5"))
        self.label_14.setText(_translate("Form", "%"))
        self.widget_8.setProperty("state", _translate("Form", "symbol"))
        self.label_15.setText(_translate("Form", "6"))
        self.label_16.setText(_translate("Form", "^"))
        self.widget_9.setProperty("state", _translate("Form", "symbol"))
        self.label_17.setText(_translate("Form", "7"))
        self.label_18.setText(_translate("Form", "&"))
        self.widget_10.setProperty("state", _translate("Form", "symbol"))
        self.label_19.setText(_translate("Form", "8"))
        self.label_20.setText(_translate("Form", "*"))
        self.widget_11.setProperty("state", _translate("Form", "symbol"))
        self.label_21.setText(_translate("Form", "9"))
        self.label_22.setText(_translate("Form", "("))
        self.widget_12.setProperty("state", _translate("Form", "symbol"))
        self.label_23.setText(_translate("Form", "0"))
        self.label_24.setText(_translate("Form", ")"))
        self.pushButton.setText(_translate("Form", "←"))
        self.pushButton.setProperty("state", _translate("Form", "delPreStr"))
        self.btnClose.setText(_translate("Form", "×"))
        self.pushButton_3.setText(_translate("Form", "Caps Lock"))
        self.pushButton_3.setProperty("state", _translate("Form", "capsLock"))
        self.widget_13.setProperty("state", _translate("Form", "symbol"))
        self.label_25.setText(_translate("Form", "-"))
        self.label_26.setText(_translate("Form", "—"))
        self.widget_14.setProperty("state", _translate("Form", "symbol"))
        self.label_27.setText(_translate("Form", "="))
        self.label_28.setText(_translate("Form", "+"))
        self.widget_15.setProperty("state", _translate("Form", "symbol"))
        self.label_29.setText(_translate("Form", "["))
        self.label_30.setText(_translate("Form", "{"))
        self.widget_16.setProperty("state", _translate("Form", "symbol"))
        self.label_31.setText(_translate("Form", "]"))
        self.label_32.setText(_translate("Form", "}"))
        self.widget_22.setProperty("state", _translate("Form", "symbol"))
        self.label_43.setText(_translate("Form", "\\"))
        self.label_44.setText(_translate("Form", "|"))
        self.widget_17.setProperty("state", _translate("Form", "symbol"))
        self.label_33.setText(_translate("Form", ";"))
        self.label_34.setText(_translate("Form", ":"))
        self.widget_18.setProperty("state", _translate("Form", "symbol"))
        self.label_35.setText(_translate("Form", "\'"))
        self.label_36.setText(_translate("Form", "\""))
        self.widget_19.setProperty("state", _translate("Form", "symbol"))
        self.label_37.setText(_translate("Form", ","))
        self.label_38.setText(_translate("Form", "<"))
        self.widget_20.setProperty("state", _translate("Form", "symbol"))
        self.label_39.setText(_translate("Form", "."))
        self.label_40.setText(_translate("Form", ">"))
        self.widget_21.setProperty("state", _translate("Form", "symbol"))
        self.label_41.setText(_translate("Form", "/"))
        self.label_42.setText(_translate("Form", "?"))
        self.pushButton_4.setText(_translate("Form", "Shift"))
        self.pushButton_4.setProperty("state", _translate("Form", "shift"))
        self.pushButton_5.setText(_translate("Form", "a"))
        self.pushButton_5.setProperty("state", _translate("Form", "letter"))
        self.pushButton_6.setText(_translate("Form", "b"))
        self.pushButton_6.setProperty("state", _translate("Form", "letter"))
        self.pushButton_7.setText(_translate("Form", "c"))
        self.pushButton_7.setProperty("state", _translate("Form", "letter"))
        self.pushButton_8.setText(_translate("Form", "d"))
        self.pushButton_8.setProperty("state", _translate("Form", "letter"))
        self.pushButton_9.setText(_translate("Form", "e"))
        self.pushButton_9.setProperty("state", _translate("Form", "letter"))
        self.pushButton_10.setText(_translate("Form", "f"))
        self.pushButton_10.setProperty("state", _translate("Form", "letter"))
        self.pushButton_11.setText(_translate("Form", "g"))
        self.pushButton_11.setProperty("state", _translate("Form", "letter"))
        self.pushButton_12.setText(_translate("Form", "h"))
        self.pushButton_12.setProperty("state", _translate("Form", "letter"))
        self.pushButton_13.setText(_translate("Form", "i"))
        self.pushButton_13.setProperty("state", _translate("Form", "letter"))
        self.pushButton_14.setText(_translate("Form", "j"))
        self.pushButton_14.setProperty("state", _translate("Form", "letter"))
        self.pushButton_15.setText(_translate("Form", "k"))
        self.pushButton_15.setProperty("state", _translate("Form", "letter"))
        self.pushButton_16.setText(_translate("Form", "l"))
        self.pushButton_16.setProperty("state", _translate("Form", "letter"))
        self.pushButton_17.setText(_translate("Form", "m"))
        self.pushButton_17.setProperty("state", _translate("Form", "letter"))
        self.pushButton_27.setText(_translate("Form", "n"))
        self.pushButton_27.setProperty("state", _translate("Form", "letter"))
        self.pushButton_22.setText(_translate("Form", "o"))
        self.pushButton_22.setProperty("state", _translate("Form", "letter"))
        self.pushButton_28.setText(_translate("Form", "p"))
        self.pushButton_28.setProperty("state", _translate("Form", "letter"))
        self.pushButton_19.setText(_translate("Form", "q"))
        self.pushButton_19.setProperty("state", _translate("Form", "letter"))
        self.pushButton_26.setText(_translate("Form", "r"))
        self.pushButton_26.setProperty("state", _translate("Form", "letter"))
        self.pushButton_29.setText(_translate("Form", "s"))
        self.pushButton_29.setProperty("state", _translate("Form", "letter"))
        self.pushButton_23.setText(_translate("Form", "t"))
        self.pushButton_23.setProperty("state", _translate("Form", "letter"))
        self.pushButton_24.setText(_translate("Form", "u"))
        self.pushButton_24.setProperty("state", _translate("Form", "letter"))
        self.pushButton_18.setText(_translate("Form", "v"))
        self.pushButton_18.setProperty("state", _translate("Form", "letter"))
        self.pushButton_30.setText(_translate("Form", "w"))
        self.pushButton_30.setProperty("state", _translate("Form", "letter"))
        self.pushButton_25.setText(_translate("Form", "x"))
        self.pushButton_25.setProperty("state", _translate("Form", "letter"))
        self.pushButton_20.setText(_translate("Form", "y"))
        self.pushButton_20.setProperty("state", _translate("Form", "letter"))
        self.pushButton_21.setText(_translate("Form", "z"))
        self.pushButton_21.setProperty("state", _translate("Form", "letter"))
from login.keyboardBtn import KeyboardBtn
