# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnMini = QtWidgets.QPushButton(Form)
        self.btnMini.setMinimumSize(QtCore.QSize(30, 30))
        self.btnMini.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnMini.setFont(font)
        self.btnMini.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMini.setObjectName("btnMini")
        self.horizontalLayout.addWidget(self.btnMini, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.btnExit = QtWidgets.QPushButton(Form)
        self.btnExit.setMinimumSize(QtCore.QSize(30, 30))
        self.btnExit.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnExit.setFont(font)
        self.btnExit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labUserAvatar = QtWidgets.QLabel(Form)
        self.labUserAvatar.setMinimumSize(QtCore.QSize(70, 70))
        self.labUserAvatar.setMaximumSize(QtCore.QSize(70, 70))
        self.labUserAvatar.setStyleSheet("")
        self.labUserAvatar.setText("")
        self.labUserAvatar.setObjectName("labUserAvatar")
        self.verticalLayout.addWidget(self.labUserAvatar, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(75, -1, 75, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.comboAccount = ComboBox(Form)
        self.comboAccount.setMinimumSize(QtCore.QSize(250, 30))
        self.comboAccount.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.comboAccount.setFont(font)
        self.comboAccount.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboAccount.setEditable(True)
        self.comboAccount.setObjectName("comboAccount")
        self.gridLayout.addWidget(self.comboAccount, 0, 0, 1, 3)
        self.lePassword = QtWidgets.QLineEdit(Form)
        self.lePassword.setMinimumSize(QtCore.QSize(250, 30))
        self.lePassword.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lePassword.setFont(font)
        self.lePassword.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lePassword.setText("")
        self.lePassword.setMaxLength(11)
        self.lePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePassword.setObjectName("lePassword")
        self.gridLayout.addWidget(self.lePassword, 1, 0, 1, 3)
        self.ckAotuLogin = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckAotuLogin.sizePolicy().hasHeightForWidth())
        self.ckAotuLogin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.ckAotuLogin.setFont(font)
        self.ckAotuLogin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ckAotuLogin.setObjectName("ckAotuLogin")
        self.gridLayout.addWidget(self.ckAotuLogin, 2, 0, 1, 1)
        self.ckKeepPassword = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckKeepPassword.sizePolicy().hasHeightForWidth())
        self.ckKeepPassword.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.ckKeepPassword.setFont(font)
        self.ckKeepPassword.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ckKeepPassword.setObjectName("ckKeepPassword")
        self.gridLayout.addWidget(self.ckKeepPassword, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.btnRegister = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegister.sizePolicy().hasHeightForWidth())
        self.btnRegister.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.btnRegister.setFont(font)
        self.btnRegister.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRegister.setObjectName("btnRegister")
        self.gridLayout.addWidget(self.btnRegister, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.btnVisitorLogin = QtWidgets.QPushButton(Form)
        self.btnVisitorLogin.setMinimumSize(QtCore.QSize(0, 35))
        self.btnVisitorLogin.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnVisitorLogin.setFont(font)
        self.btnVisitorLogin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnVisitorLogin.setObjectName("btnVisitorLogin")
        self.gridLayout.addWidget(self.btnVisitorLogin, 3, 0, 1, 1)
        self.btnLogin = QtWidgets.QPushButton(Form)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 35))
        self.btnLogin.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login/images/login_icon_login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogin.setIcon(icon)
        self.btnLogin.setIconSize(QtCore.QSize(20, 20))
        self.btnLogin.setObjectName("btnLogin")
        self.gridLayout.addWidget(self.btnLogin, 3, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        self.btnExit.clicked.connect(Form.close)
        self.btnMini.clicked.connect(Form.showMinimized)
        self.btnLogin.clicked.connect(Form.checkLogin)
        self.comboAccount.editTextChanged['QString'].connect(self.lePassword.clear)
        self.lePassword.textChanged['QString'].connect(Form.checkForNull)
        self.btnRegister.clicked.connect(Form.showRegisterPane)
        Form.returnPressedSignal.connect(self.btnLogin.click)
        self.comboAccount.finished.connect(self.lePassword.setFocus)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnMini.setText(_translate("Form", "—"))
        self.btnExit.setText(_translate("Form", "×"))
        self.lePassword.setPlaceholderText(_translate("Form", "密码"))
        self.ckAotuLogin.setText(_translate("Form", "自动登录"))
        self.ckKeepPassword.setText(_translate("Form", "记住密码"))
        self.btnRegister.setText(_translate("Form", "快速注册"))
        self.btnVisitorLogin.setText(_translate("Form", "游客登录"))
        self.btnLogin.setText(_translate("Form", "登录"))
from login.comboBox import ComboBox
from login.resource import images_rc
