# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        Form.setStyleSheet("")
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(50, -1, 50, -1)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.labRegisterError = QtWidgets.QLabel(Form)
        self.labRegisterError.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.labRegisterError.setFont(font)
        self.labRegisterError.setAlignment(QtCore.Qt.AlignCenter)
        self.labRegisterError.setObjectName("labRegisterError")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.labRegisterError)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.leAccount = QtWidgets.QLineEdit(Form)
        self.leAccount.setMinimumSize(QtCore.QSize(0, 30))
        self.leAccount.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.leAccount.setObjectName("leAccount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leAccount)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lePassword = QtWidgets.QLineEdit(Form)
        self.lePassword.setMinimumSize(QtCore.QSize(0, 30))
        self.lePassword.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lePassword.setObjectName("lePassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lePassword)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.leNickname = QtWidgets.QLineEdit(Form)
        self.leNickname.setMinimumSize(QtCore.QSize(0, 30))
        self.leNickname.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.leNickname.setObjectName("leNickname")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.leNickname)
        self.btnExit = QtWidgets.QPushButton(Form)
        self.btnExit.setMinimumSize(QtCore.QSize(0, 35))
        self.btnExit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.btnExit.setFont(font)
        self.btnExit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnExit.setObjectName("btnExit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.btnExit)
        self.btnRegister = QtWidgets.QPushButton(Form)
        self.btnRegister.setMinimumSize(QtCore.QSize(0, 35))
        self.btnRegister.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.btnRegister.setFont(font)
        self.btnRegister.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnRegister.setObjectName("btnRegister")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnRegister)

        self.retranslateUi(Form)
        self.btnExit.clicked.connect(Form.exitPane)
        self.btnRegister.clicked.connect(Form.checkRegister)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labRegisterError.setText(_translate("Form", "*账号名重复"))
        self.label.setText(_translate("Form", "账号："))
        self.label_3.setText(_translate("Form", "密码："))
        self.label_2.setText(_translate("Form", "昵称："))
        self.btnExit.setText(_translate("Form", "返回"))
        self.btnRegister.setText(_translate("Form", "注册"))
