# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Login.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 300)
        Login.setMinimumSize(QtCore.QSize(400, 300))
        Login.setMaximumSize(QtCore.QSize(400, 300))
        self.labBg = QtWidgets.QLabel(Login)
        self.labBg.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.labBg.setText("")
        self.labBg.setScaledContents(True)
        self.labBg.setObjectName("labBg")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Login)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnMini = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnMini.setMinimumSize(QtCore.QSize(30, 30))
        self.btnMini.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnMini.setFont(font)
        self.btnMini.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMini.setObjectName("btnMini")
        self.horizontalLayout.addWidget(self.btnMini)
        self.btnExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnExit.setMinimumSize(QtCore.QSize(30, 30))
        self.btnExit.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnExit.setFont(font)
        self.btnExit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit)
        self.widLogin = QtWidgets.QWidget(Login)
        self.widLogin.setGeometry(QtCore.QRect(0, 100, 400, 200))
        self.widLogin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widLogin.setObjectName("widLogin")
        self.gridLayout = QtWidgets.QGridLayout(self.widLogin)
        self.gridLayout.setContentsMargins(75, 60, 75, 10)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.btnVisitorLogin = QtWidgets.QPushButton(self.widLogin)
        self.btnVisitorLogin.setMinimumSize(QtCore.QSize(0, 35))
        self.btnVisitorLogin.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnVisitorLogin.setFont(font)
        self.btnVisitorLogin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnVisitorLogin.setObjectName("btnVisitorLogin")
        self.gridLayout.addWidget(self.btnVisitorLogin, 3, 0, 1, 1)
        self.btnVipLogin = QtWidgets.QPushButton(self.widLogin)
        self.btnVipLogin.setMinimumSize(QtCore.QSize(0, 35))
        self.btnVipLogin.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btnVipLogin.setFont(font)
        self.btnVipLogin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnVipLogin.setObjectName("btnVipLogin")
        self.gridLayout.addWidget(self.btnVipLogin, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cBoxAotuLogin = QtWidgets.QCheckBox(self.widLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBoxAotuLogin.sizePolicy().hasHeightForWidth())
        self.cBoxAotuLogin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.cBoxAotuLogin.setFont(font)
        self.cBoxAotuLogin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxAotuLogin.setObjectName("cBoxAotuLogin")
        self.horizontalLayout_4.addWidget(self.cBoxAotuLogin)
        self.cBoxKeepPswd = QtWidgets.QCheckBox(self.widLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBoxKeepPswd.sizePolicy().hasHeightForWidth())
        self.cBoxKeepPswd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.cBoxKeepPswd.setFont(font)
        self.cBoxKeepPswd.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxKeepPswd.setObjectName("cBoxKeepPswd")
        self.horizontalLayout_4.addWidget(self.cBoxKeepPswd)
        self.btnSignIn = QtWidgets.QPushButton(self.widLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSignIn.sizePolicy().hasHeightForWidth())
        self.btnSignIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.btnSignIn.setFont(font)
        self.btnSignIn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSignIn.setObjectName("btnSignIn")
        self.horizontalLayout_4.addWidget(self.btnSignIn)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        self.lineEdUserPswd = QtWidgets.QLineEdit(self.widLogin)
        self.lineEdUserPswd.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdUserPswd.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdUserPswd.setFont(font)
        self.lineEdUserPswd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdUserPswd.setText("")
        self.lineEdUserPswd.setMaxLength(11)
        self.lineEdUserPswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdUserPswd.setObjectName("lineEdUserPswd")
        self.gridLayout.addWidget(self.lineEdUserPswd, 1, 0, 1, 2)
        self.comboUserID = QtWidgets.QComboBox(self.widLogin)
        self.comboUserID.setMinimumSize(QtCore.QSize(0, 30))
        self.comboUserID.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.comboUserID.setFont(font)
        self.comboUserID.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboUserID.setEditable(True)
        self.comboUserID.setObjectName("comboUserID")
        self.gridLayout.addWidget(self.comboUserID, 0, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Login)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 63, 401, 76))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widUserpic = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.widUserpic.setMinimumSize(QtCore.QSize(74, 74))
        self.widUserpic.setMaximumSize(QtCore.QSize(74, 74))
        self.widUserpic.setObjectName("widUserpic")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widUserpic)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labUserpic = QtWidgets.QLabel(self.widUserpic)
        self.labUserpic.setText("")
        self.labUserpic.setObjectName("labUserpic")
        self.horizontalLayout_2.addWidget(self.labUserpic)
        self.horizontalLayout_3.addWidget(self.widUserpic)
        self.labLoginError = QtWidgets.QLabel(Login)
        self.labLoginError.setGeometry(QtCore.QRect(330, 162, 54, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labLoginError.setFont(font)
        self.labLoginError.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labLoginError.setObjectName("labLoginError")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.btnMini.setText(_translate("Login", "—"))
        self.btnExit.setText(_translate("Login", "×"))
        self.btnVisitorLogin.setText(_translate("Login", "游客登录"))
        self.btnVipLogin.setText(_translate("Login", "登录"))
        self.cBoxAotuLogin.setText(_translate("Login", "自动登录"))
        self.cBoxKeepPswd.setText(_translate("Login", "记住密码"))
        self.btnSignIn.setText(_translate("Login", "快速注册"))
        self.lineEdUserPswd.setPlaceholderText(_translate("Login", "密码"))
        self.labLoginError.setText(_translate("Login", "账户名\n"
"或密码\n"
"错误！"))


