# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Register.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(400, 300)
        Register.setMinimumSize(QtCore.QSize(400, 300))
        Register.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setPointSize(1)
        Register.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Register)
        self.gridLayout.setContentsMargins(50, 0, 50, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labRegisterError = QtWidgets.QLabel(Register)
        self.labRegisterError.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.labRegisterError.setFont(font)
        self.labRegisterError.setAlignment(QtCore.Qt.AlignCenter)
        self.labRegisterError.setObjectName("labRegisterError")
        self.gridLayout.addWidget(self.labRegisterError, 0, 0, 1, 2)
        self.lineEdNickname = QtWidgets.QLineEdit(Register)
        self.lineEdNickname.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdNickname.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdNickname.setObjectName("lineEdNickname")
        self.gridLayout.addWidget(self.lineEdNickname, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Register)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdPswd = QtWidgets.QLineEdit(Register)
        self.lineEdPswd.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdPswd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdPswd.setObjectName("lineEdPswd")
        self.gridLayout.addWidget(self.lineEdPswd, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Register)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdID = QtWidgets.QLineEdit(Register)
        self.lineEdID.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdID.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdID.setObjectName("lineEdID")
        self.gridLayout.addWidget(self.lineEdID, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Register)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.btnBack = QtWidgets.QPushButton(Register)
        self.btnBack.setMinimumSize(QtCore.QSize(0, 35))
        self.btnBack.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.btnBack.setFont(font)
        self.btnBack.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 4, 0, 1, 1)
        self.btnRegister = QtWidgets.QPushButton(Register)
        self.btnRegister.setMinimumSize(QtCore.QSize(0, 35))
        self.btnRegister.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.btnRegister.setFont(font)
        self.btnRegister.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnRegister.setObjectName("btnRegister")
        self.gridLayout.addWidget(self.btnRegister, 4, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Dialog"))
        self.labRegisterError.setText(_translate("Register", "*账号名重复"))
        self.label_2.setText(_translate("Register", "昵称："))
        self.label_3.setText(_translate("Register", "密码："))
        self.label.setText(_translate("Register", "账号："))
        self.btnBack.setText(_translate("Register", "返回"))
        self.btnRegister.setText(_translate("Register", "注册"))


