# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'collect.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Card(object):
    def setupUi(self, Card):
        Card.setObjectName("Card")
        Card.resize(884, 680)
        self.verticalLayout = QtWidgets.QVBoxLayout(Card)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widTitle = QtWidgets.QWidget(Card)
        self.widTitle.setMinimumSize(QtCore.QSize(0, 30))
        self.widTitle.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.widTitle.setObjectName("widTitle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widTitle)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widTitle)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.widTitle)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.labTitle = QtWidgets.QLabel(self.widTitle)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.labTitle.setFont(font)
        self.labTitle.setObjectName("labTitle")
        self.horizontalLayout.addWidget(self.labTitle)
        self.label_4 = QtWidgets.QLabel(self.widTitle)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnClose = QtWidgets.QPushButton(self.widTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnClose.setFont(font)
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addWidget(self.widTitle)
        self.scrollArea = QtWidgets.QScrollArea(Card)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWid = QtWidgets.QWidget()
        self.scrollAreaWid.setGeometry(QtCore.QRect(0, 0, 882, 643))
        self.scrollAreaWid.setObjectName("scrollAreaWid")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWid)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWid)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Card)
        self.btnClose.clicked.connect(Card.close)
        QtCore.QMetaObject.connectSlotsByName(Card)

    def retranslateUi(self, Card):
        _translate = QtCore.QCoreApplication.translate
        Card.setWindowTitle(_translate("Card", "Dialog"))
        self.label.setText(_translate("Card", "我的卡藏"))
        self.label_2.setText(_translate("Card", "共获得 "))
        self.labTitle.setText(_translate("Card", "1052"))
        self.label_4.setText(_translate("Card", " 张卡片"))
        self.btnClose.setText(_translate("Card", "×"))
