# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(980, 700)
        Main.setMinimumSize(QtCore.QSize(980, 700))
        Main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Main.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Main.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widTitle = QtWidgets.QWidget(Main)
        self.widTitle.setMinimumSize(QtCore.QSize(0, 80))
        self.widTitle.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.widTitle.setObjectName("widTitle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widTitle)
        self.horizontalLayout_4.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnLogo = QtWidgets.QPushButton(self.widTitle)
        self.btnLogo.setMinimumSize(QtCore.QSize(138, 50))
        self.btnLogo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnLogo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogo.setIcon(icon)
        self.btnLogo.setIconSize(QtCore.QSize(138, 50))
        self.btnLogo.setProperty("pageIndex", 0)
        self.btnLogo.setObjectName("btnLogo")
        self.horizontalLayout_4.addWidget(self.btnLogo)
        spacerItem = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.labGoldPix = QtWidgets.QLabel(self.widTitle)
        self.labGoldPix.setMinimumSize(QtCore.QSize(40, 40))
        self.labGoldPix.setMaximumSize(QtCore.QSize(40, 40))
        self.labGoldPix.setText("")
        self.labGoldPix.setObjectName("labGoldPix")
        self.horizontalLayout_4.addWidget(self.labGoldPix)
        self.labGoldCount = QtWidgets.QLabel(self.widTitle)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.labGoldCount.setFont(font)
        self.labGoldCount.setObjectName("labGoldCount")
        self.horizontalLayout_4.addWidget(self.labGoldCount)
        self.labJewelPix = QtWidgets.QLabel(self.widTitle)
        self.labJewelPix.setMinimumSize(QtCore.QSize(40, 40))
        self.labJewelPix.setMaximumSize(QtCore.QSize(40, 40))
        self.labJewelPix.setText("")
        self.labJewelPix.setObjectName("labJewelPix")
        self.horizontalLayout_4.addWidget(self.labJewelPix)
        self.labJewelCount = QtWidgets.QLabel(self.widTitle)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.labJewelCount.setFont(font)
        self.labJewelCount.setObjectName("labJewelCount")
        self.horizontalLayout_4.addWidget(self.labJewelCount)
        spacerItem1 = QtWidgets.QSpacerItem(247, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 3, 5, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAvatar = QtWidgets.QPushButton(self.widTitle)
        self.btnAvatar.setMinimumSize(QtCore.QSize(60, 17))
        self.btnAvatar.setMaximumSize(QtCore.QSize(60, 17))
        self.btnAvatar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAvatar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnAvatar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/images/icon_avatar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAvatar.setIcon(icon1)
        self.btnAvatar.setIconSize(QtCore.QSize(13, 13))
        self.btnAvatar.setObjectName("btnAvatar")
        self.horizontalLayout_2.addWidget(self.btnAvatar, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widTitle)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 20))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 20))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/images/icon_collect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignTop)
        self.pushButton_5 = QtWidgets.QPushButton(self.widTitle)
        self.pushButton_5.setMinimumSize(QtCore.QSize(30, 20))
        self.pushButton_5.setMaximumSize(QtCore.QSize(30, 20))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/images/icon_shop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignTop)
        self.pushButton_3 = QtWidgets.QPushButton(self.widTitle)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 20))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 20))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/main/images/icon_skin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignTop)
        self.pushButton_2 = QtWidgets.QPushButton(self.widTitle)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 20))
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/main/images/icon_mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignTop)
        self.pushButton_6 = QtWidgets.QPushButton(self.widTitle)
        self.pushButton_6.setMinimumSize(QtCore.QSize(30, 20))
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/main/images/icon_max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/main/images/icon_normal.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignTop)
        self.pushButton = QtWidgets.QPushButton(self.widTitle)
        self.pushButton.setMinimumSize(QtCore.QSize(35, 20))
        self.pushButton.setMaximumSize(QtCore.QSize(35, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/main/images/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.widTitle)
        self.widContent = QtWidgets.QWidget(Main)
        self.widContent.setObjectName("widContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widContent)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widHello = QtWidgets.QWidget(self.widContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widHello.sizePolicy().hasHeightForWidth())
        self.widHello.setSizePolicy(sizePolicy)
        self.widHello.setObjectName("widHello")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widHello)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widBack = QtWidgets.QWidget(self.widHello)
        self.widBack.setObjectName("widBack")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widBack)
        self.horizontalLayout.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnBack = QtWidgets.QPushButton(self.widBack)
        self.btnBack.setMinimumSize(QtCore.QSize(75, 26))
        self.btnBack.setMaximumSize(QtCore.QSize(75, 26))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnBack.setFont(font)
        self.btnBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBack.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnBack.setText("")
        self.btnBack.setProperty("pageIndex", 0)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout.addWidget(self.btnBack)
        self.labBackLink = QtWidgets.QLabel(self.widBack)
        self.labBackLink.setMinimumSize(QtCore.QSize(600, 0))
        self.labBackLink.setOpenExternalLinks(False)
        self.labBackLink.setObjectName("labBackLink")
        self.horizontalLayout.addWidget(self.labBackLink)
        self.btnMenu = QtWidgets.QPushButton(self.widBack)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu.sizePolicy().hasHeightForWidth())
        self.btnMenu.setSizePolicy(sizePolicy)
        self.btnMenu.setMinimumSize(QtCore.QSize(120, 0))
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout.addWidget(self.btnMenu)
        self.verticalLayout_2.addWidget(self.widBack)
        self.labHello = QtWidgets.QLabel(self.widHello)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labHello.sizePolicy().hasHeightForWidth())
        self.labHello.setSizePolicy(sizePolicy)
        self.labHello.setStyleSheet("")
        self.labHello.setAlignment(QtCore.Qt.AlignCenter)
        self.labHello.setObjectName("labHello")
        self.verticalLayout_2.addWidget(self.labHello)
        self.verticalLayout.addWidget(self.widHello)
        self.stkWid = QtWidgets.QStackedWidget(self.widContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stkWid.sizePolicy().hasHeightForWidth())
        self.stkWid.setSizePolicy(sizePolicy)
        self.stkWid.setMinimumSize(QtCore.QSize(0, 370))
        self.stkWid.setMaximumSize(QtCore.QSize(16777215, 370))
        self.stkWid.setObjectName("stkWid")
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.gridLayout = QtWidgets.QGridLayout(self.pageHome)
        self.gridLayout.setObjectName("gridLayout")
        self.btnCn = QtWidgets.QPushButton(self.pageHome)
        self.btnCn.setMinimumSize(QtCore.QSize(163, 163))
        self.btnCn.setMaximumSize(QtCore.QSize(163, 163))
        self.btnCn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCn.setStyleSheet("")
        self.btnCn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/main/images/icon_cn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCn.setIcon(icon8)
        self.btnCn.setIconSize(QtCore.QSize(163, 163))
        self.btnCn.setProperty("pageIndex", 1)
        self.btnCn.setObjectName("btnCn")
        self.gridLayout.addWidget(self.btnCn, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.pageHome)
        self.line.setAutoFillBackground(False)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 2, 4)
        self.label_2 = QtWidgets.QLabel(self.pageHome)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.pageHome)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.btnGame = QtWidgets.QPushButton(self.pageHome)
        self.btnGame.setMinimumSize(QtCore.QSize(163, 163))
        self.btnGame.setMaximumSize(QtCore.QSize(163, 163))
        self.btnGame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnGame.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/main/images/icon_game.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGame.setIcon(icon9)
        self.btnGame.setIconSize(QtCore.QSize(163, 163))
        self.btnGame.setProperty("pageIndex", 4)
        self.btnGame.setObjectName("btnGame")
        self.gridLayout.addWidget(self.btnGame, 3, 1, 1, 1)
        self.btnMath = QtWidgets.QPushButton(self.pageHome)
        self.btnMath.setMinimumSize(QtCore.QSize(163, 163))
        self.btnMath.setMaximumSize(QtCore.QSize(163, 163))
        self.btnMath.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMath.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMath.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/main/images/icon_math.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMath.setIcon(icon10)
        self.btnMath.setIconSize(QtCore.QSize(163, 163))
        self.btnMath.setProperty("pageIndex", 2)
        self.btnMath.setObjectName("btnMath")
        self.gridLayout.addWidget(self.btnMath, 0, 2, 1, 1)
        self.btnMusic = QtWidgets.QPushButton(self.pageHome)
        self.btnMusic.setMinimumSize(QtCore.QSize(163, 163))
        self.btnMusic.setMaximumSize(QtCore.QSize(163, 163))
        self.btnMusic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMusic.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMusic.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/main/images/icon_music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMusic.setIcon(icon11)
        self.btnMusic.setIconSize(QtCore.QSize(163, 163))
        self.btnMusic.setProperty("pageIndex", 6)
        self.btnMusic.setObjectName("btnMusic")
        self.gridLayout.addWidget(self.btnMusic, 3, 3, 1, 1)
        self.btnEn = QtWidgets.QPushButton(self.pageHome)
        self.btnEn.setMinimumSize(QtCore.QSize(163, 163))
        self.btnEn.setMaximumSize(QtCore.QSize(163, 163))
        self.btnEn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEn.setStyleSheet("qradialgradient:(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255))")
        self.btnEn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/main/images/icon_en.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEn.setIcon(icon12)
        self.btnEn.setIconSize(QtCore.QSize(163, 163))
        self.btnEn.setProperty("pageIndex", 3)
        self.btnEn.setObjectName("btnEn")
        self.gridLayout.addWidget(self.btnEn, 0, 3, 1, 1)
        self.btnMovie = QtWidgets.QPushButton(self.pageHome)
        self.btnMovie.setMinimumSize(QtCore.QSize(163, 163))
        self.btnMovie.setMaximumSize(QtCore.QSize(163, 163))
        self.btnMovie.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMovie.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMovie.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/main/images/icon_movie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMovie.setIcon(icon13)
        self.btnMovie.setIconSize(QtCore.QSize(163, 163))
        self.btnMovie.setProperty("pageIndex", 5)
        self.btnMovie.setObjectName("btnMovie")
        self.gridLayout.addWidget(self.btnMovie, 3, 2, 1, 1)
        self.stkWid.addWidget(self.pageHome)
        self.pageCn = QtWidgets.QWidget()
        self.pageCn.setObjectName("pageCn")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.pageCn)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.pageCn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 978, 368))
        self.page_1.setObjectName("page_1")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.scrollArea.setWidget(self.page_1)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        self.stkWid.addWidget(self.pageCn)
        self.pageMath = QtWidgets.QWidget()
        self.pageMath.setObjectName("pageMath")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.pageMath)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.pageMath)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 978, 368))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.addWidget(self.scrollArea_2)
        self.stkWid.addWidget(self.pageMath)
        self.pageEn = QtWidgets.QWidget()
        self.pageEn.setObjectName("pageEn")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.pageEn)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.pageEn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 978, 368))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_9.addWidget(self.scrollArea_3)
        self.stkWid.addWidget(self.pageEn)
        self.pageGames = QtWidgets.QWidget()
        self.pageGames.setObjectName("pageGames")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pageGames)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.pageGames)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 978, 368))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_3.addWidget(self.scrollArea_4)
        self.stkWid.addWidget(self.pageGames)
        self.pageMusic = QtWidgets.QWidget()
        self.pageMusic.setObjectName("pageMusic")
        self.pushButton_26 = QtWidgets.QPushButton(self.pageMusic)
        self.pushButton_26.setGeometry(QtCore.QRect(124, 103, 163, 163))
        self.pushButton_26.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_26.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_26.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_26.setStyleSheet("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.pageMusic)
        self.pushButton_27.setGeometry(QtCore.QRect(408, 103, 163, 163))
        self.pushButton_27.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_27.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_27.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_27.setStyleSheet("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.pageMusic)
        self.pushButton_28.setGeometry(QtCore.QRect(692, 103, 163, 163))
        self.pushButton_28.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_28.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_28.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_28.setStyleSheet("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.stkWid.addWidget(self.pageMusic)
        self.pageMovie = QtWidgets.QWidget()
        self.pageMovie.setObjectName("pageMovie")
        self.pushButton_29 = QtWidgets.QPushButton(self.pageMovie)
        self.pushButton_29.setGeometry(QtCore.QRect(124, 103, 163, 163))
        self.pushButton_29.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_29.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_29.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_29.setStyleSheet("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.pageMovie)
        self.pushButton_30.setGeometry(QtCore.QRect(408, 103, 163, 163))
        self.pushButton_30.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_30.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_30.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_30.setStyleSheet("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.pageMovie)
        self.pushButton_31.setGeometry(QtCore.QRect(692, 103, 163, 163))
        self.pushButton_31.setMinimumSize(QtCore.QSize(163, 163))
        self.pushButton_31.setMaximumSize(QtCore.QSize(163, 163))
        self.pushButton_31.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_31.setStyleSheet("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.stkWid.addWidget(self.pageMovie)
        self.verticalLayout.addWidget(self.stkWid)
        self.verticalLayout_3.addWidget(self.widContent)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.labStatusTip = QtWidgets.QLabel(Main)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labStatusTip.setFont(font)
        self.labStatusTip.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labStatusTip.setObjectName("labStatusTip")
        self.horizontalLayout_12.addWidget(self.labStatusTip)
        self.btnStatusTip = QtWidgets.QPushButton(Main)
        self.btnStatusTip.setMaximumSize(QtCore.QSize(30, 30))
        self.btnStatusTip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStatusTip.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnStatusTip.setText("")
        self.btnStatusTip.setObjectName("btnStatusTip")
        self.horizontalLayout_12.addWidget(self.btnStatusTip)
        self.btnStatusTipChange = QtWidgets.QPushButton(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStatusTipChange.sizePolicy().hasHeightForWidth())
        self.btnStatusTipChange.setSizePolicy(sizePolicy)
        self.btnStatusTipChange.setMinimumSize(QtCore.QSize(10, 0))
        self.btnStatusTipChange.setMaximumSize(QtCore.QSize(10, 16777215))
        self.btnStatusTipChange.setText("")
        self.btnStatusTipChange.setObjectName("btnStatusTipChange")
        self.horizontalLayout_12.addWidget(self.btnStatusTipChange)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.setStretch(1, 15)
        self.verticalLayout_3.setStretch(2, 1)

        self.retranslateUi(Main)
        self.stkWid.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(Main.showMinimized)
        self.pushButton.clicked.connect(Main.close)
        self.pushButton_3.clicked.connect(Main.showSkins)
        self.pushButton_4.clicked.connect(Main.showCollect)
        self.pushButton_5.clicked.connect(Main.showShop)
        self.btnCn.clicked.connect(Main.changePage)
        self.btnMath.clicked.connect(Main.changePage)
        self.btnEn.clicked.connect(Main.changePage)
        self.btnGame.clicked.connect(Main.changePage)
        self.btnMovie.clicked.connect(Main.changePage)
        self.btnMusic.clicked.connect(Main.changePage)
        self.btnLogo.clicked.connect(Main.changePage)
        self.btnBack.clicked.connect(Main.changePage)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.labGoldCount.setText(_translate("Main", "0"))
        self.labJewelCount.setText(_translate("Main", "0"))
        self.btnAvatar.setProperty("titleBar", _translate("Main", "avatar"))
        self.pushButton_4.setProperty("titleBar", _translate("Main", "normal"))
        self.pushButton_5.setProperty("titleBar", _translate("Main", "normal"))
        self.pushButton_3.setProperty("titleBar", _translate("Main", "normal"))
        self.pushButton_2.setProperty("titleBar", _translate("Main", "normal"))
        self.pushButton_6.setProperty("titleBar", _translate("Main", "normal"))
        self.pushButton.setProperty("titleBar", _translate("Main", "close"))
        self.labBackLink.setText(_translate("Main", "首页>"))
        self.btnMenu.setText(_translate("Main", "课程选择"))
        self.labHello.setText(_translate("Main", "Hi,XXX!"))
        self.label_2.setText(_translate("Main", "<html><head/><body><p>学</p><p>习</p></body></html>"))
        self.label_3.setText(_translate("Main", "<html><head/><body><p>娱</p><p>乐</p></body></html>"))
        self.pushButton_26.setText(_translate("Main", "Music"))
        self.pushButton_27.setText(_translate("Main", "Music"))
        self.pushButton_28.setText(_translate("Main", "Music"))
        self.pushButton_29.setText(_translate("Main", "movies"))
        self.pushButton_30.setText(_translate("Main", "movies"))
        self.pushButton_31.setText(_translate("Main", "movies"))
        self.labStatusTip.setText(_translate("Main", "111"))
from main.resource import images_rc
